/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class consultaGeneralProductos extends javax.swing.JFrame {

    String datos[] = new String[5];
    Conexion bd;
    Statement s;
    ResultSet res;
    String query;

    /**
     * Creates new form consultaGeneralProductos
     */
    public consultaGeneralProductos() {
        initComponents();
    }
    int bandera = 0;
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaGeneralProductosEncabezado = new javax.swing.JPanel();
        consultaGeneralProductosTitulo = new javax.swing.JLabel();
        consultaGeneralProductosCuerpo = new javax.swing.JPanel();
        consultaGeneralProductosScrollPane = new javax.swing.JScrollPane();
        consultaGeneralProductosTabla = new javax.swing.JTable();
        consultaGeneralProductosPie = new javax.swing.JPanel();
        consultaGeneralProductosBotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                activarVentanaConsultaGeneralProductos(evt);
            }
        });

        consultaGeneralProductosEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProductosEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaGeneralProductosTitulo.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProductosTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        consultaGeneralProductosTitulo.setForeground(new java.awt.Color(255, 255, 255));
        consultaGeneralProductosTitulo.setText("Lista de productos");

        javax.swing.GroupLayout consultaGeneralProductosEncabezadoLayout = new javax.swing.GroupLayout(consultaGeneralProductosEncabezado);
        consultaGeneralProductosEncabezado.setLayout(consultaGeneralProductosEncabezadoLayout);
        consultaGeneralProductosEncabezadoLayout.setHorizontalGroup(
            consultaGeneralProductosEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaGeneralProductosEncabezadoLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(consultaGeneralProductosTitulo)
                .addGap(302, 302, 302))
        );
        consultaGeneralProductosEncabezadoLayout.setVerticalGroup(
            consultaGeneralProductosEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProductosEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaGeneralProductosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultaGeneralProductosCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProductosCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaGeneralProductosTabla.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProductosTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaGeneralProductosTabla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        consultaGeneralProductosTabla.setForeground(new java.awt.Color(255, 255, 255));
        consultaGeneralProductosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        consultaGeneralProductosTabla.setEnabled(false);
        consultaGeneralProductosTabla.setGridColor(new java.awt.Color(255, 255, 255));
        consultaGeneralProductosScrollPane.setViewportView(consultaGeneralProductosTabla);

        javax.swing.GroupLayout consultaGeneralProductosCuerpoLayout = new javax.swing.GroupLayout(consultaGeneralProductosCuerpo);
        consultaGeneralProductosCuerpo.setLayout(consultaGeneralProductosCuerpoLayout);
        consultaGeneralProductosCuerpoLayout.setHorizontalGroup(
            consultaGeneralProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProductosCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaGeneralProductosScrollPane)
                .addContainerGap())
        );
        consultaGeneralProductosCuerpoLayout.setVerticalGroup(
            consultaGeneralProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProductosCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaGeneralProductosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultaGeneralProductosPie.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProductosPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaGeneralProductosPie.setForeground(new java.awt.Color(255, 255, 255));

        consultaGeneralProductosBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        consultaGeneralProductosBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaGeneralProductosBotonSalir.setForeground(new java.awt.Color(0, 0, 0));
        consultaGeneralProductosBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        consultaGeneralProductosBotonSalir.setText("Salir");
        consultaGeneralProductosBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaGeneralProductosBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resaltarConsultaGeneralProductosBotonSalir(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaurarConsultaGeneralProductosBotonSalir(evt);
            }
        });
        consultaGeneralProductosBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaGeneralProductosBotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaGeneralProductosPieLayout = new javax.swing.GroupLayout(consultaGeneralProductosPie);
        consultaGeneralProductosPie.setLayout(consultaGeneralProductosPieLayout);
        consultaGeneralProductosPieLayout.setHorizontalGroup(
            consultaGeneralProductosPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProductosPieLayout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(consultaGeneralProductosBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaGeneralProductosPieLayout.setVerticalGroup(
            consultaGeneralProductosPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProductosPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaGeneralProductosBotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultaGeneralProductosEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaGeneralProductosCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaGeneralProductosPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaGeneralProductosEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaGeneralProductosCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaGeneralProductosPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaGeneralProductosBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaGeneralProductosBotonSalirActionPerformed
        // TODO add your handling code here:
        menuProductos nuevo = new menuProductos();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_consultaGeneralProductosBotonSalirActionPerformed

    public void cargarTabla() {
        modelo.addColumn("Codigo de barras");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio de compra");
        modelo.addColumn("Precio de venta");

        consultaGeneralProductosTabla.setModel(modelo);

        query = "select * from productos_existencia";

        try {

            bd = new Conexion();
            s = null;
            s = Conexion.conectar().createStatement();
            res = s.executeQuery(query);

            while (res.next()) {
                datos[0] = res.getString("ID_producto");
                datos[1] = res.getString("Nombre") + " " + res.getString("Tipo") + " " + res.getString("Tamaño");
                datos[2] = res.getString("Existencia");
                datos[3] = "$" + res.getString("Precio_compra");
                datos[4] = "$" + res.getString("Precio_venta");
                modelo.addRow(datos);
                bandera = 1;
            }

            consultaGeneralProductosTabla.setModel(modelo);

        } catch (Exception e) {

        }
    }

    private void activarVentanaConsultaGeneralProductos(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_activarVentanaConsultaGeneralProductos
        // TODO add your handling code here:
        if (bandera == 0) {
            cargarTabla();
            bandera = 1;
        }
    }//GEN-LAST:event_activarVentanaConsultaGeneralProductos

    private void resaltarConsultaGeneralProductosBotonSalir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resaltarConsultaGeneralProductosBotonSalir
        // TODO add your handling code here:
        consultaGeneralProductosBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaGeneralProductosBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarConsultaGeneralProductosBotonSalir

    private void restaurarConsultaGeneralProductosBotonSalir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurarConsultaGeneralProductosBotonSalir
        // TODO add your handling code here:
        consultaGeneralProductosBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaGeneralProductosBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarConsultaGeneralProductosBotonSalir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaGeneralProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaGeneralProductosBotonSalir;
    private javax.swing.JPanel consultaGeneralProductosCuerpo;
    private javax.swing.JPanel consultaGeneralProductosEncabezado;
    private javax.swing.JPanel consultaGeneralProductosPie;
    private javax.swing.JScrollPane consultaGeneralProductosScrollPane;
    private javax.swing.JTable consultaGeneralProductosTabla;
    private javax.swing.JLabel consultaGeneralProductosTitulo;
    // End of variables declaration//GEN-END:variables
}
