/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author David Franco
 */
public class consultaIndividualProveedores extends javax.swing.JFrame {

    String id, queryotro;
    Conexion bd;
    Statement s;
    ResultSet res;

    /**
     * Creates new form consultaIndividualProveedores
     */
    public consultaIndividualProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaIndividualProveedoresEncabezado = new javax.swing.JPanel();
        consultaIndividualProveedoresTitulo = new javax.swing.JLabel();
        consultaIndividualProveedoresCuerpo = new javax.swing.JPanel();
        consultaIndividualProveedoresID = new javax.swing.JLabel();
        consultaIndividualProveedoresEmpresa = new javax.swing.JLabel();
        consultaIndividualProveedoresTelefono = new javax.swing.JLabel();
        consultaIndividualProveedoresCorreo = new javax.swing.JLabel();
        consultaIndividualProveedoresCalle = new javax.swing.JLabel();
        consultaIndividualProveedoresNumero = new javax.swing.JLabel();
        consultaIndividualProveedoresColonia = new javax.swing.JLabel();
        consultaIndividualProveedoresEscribirEmpresa = new javax.swing.JTextField();
        consultaIndividualProveedoresEscribirID = new javax.swing.JTextField();
        consultaIndividualProveedoresEscribirCorreo = new javax.swing.JTextField();
        consultaIndividualProveedoresEscribirTelefono = new javax.swing.JTextField();
        consultaIndividualProveedoresEscribirCalle = new javax.swing.JTextField();
        consultaIndividualProveedoresEscribirNumero = new javax.swing.JTextField();
        consultaIndividualProveedoresEscribirColonia = new javax.swing.JTextField();
        consultaIndividualProveedoresBotonBuscar = new javax.swing.JButton();
        consultaIndividualProveedoresPie = new javax.swing.JPanel();
        consultaIndividualProveedoresBotonLimpiar = new javax.swing.JButton();
        consultaIndividualProveedoresBotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        consultaIndividualProveedoresEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        consultaIndividualProveedoresTitulo.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        consultaIndividualProveedoresTitulo.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresTitulo.setText("Buscar proveedores");
        consultaIndividualProveedoresTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout consultaIndividualProveedoresEncabezadoLayout = new javax.swing.GroupLayout(consultaIndividualProveedoresEncabezado);
        consultaIndividualProveedoresEncabezado.setLayout(consultaIndividualProveedoresEncabezadoLayout);
        consultaIndividualProveedoresEncabezadoLayout.setHorizontalGroup(
            consultaIndividualProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualProveedoresEncabezadoLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(consultaIndividualProveedoresTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaIndividualProveedoresEncabezadoLayout.setVerticalGroup(
            consultaIndividualProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaIndividualProveedoresEncabezadoLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(consultaIndividualProveedoresTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        consultaIndividualProveedoresCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresCuerpo.setForeground(new java.awt.Color(255, 255, 255));

        consultaIndividualProveedoresID.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresID.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresID.setText("ID del proveedor");
        consultaIndividualProveedoresID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresEmpresa.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresEmpresa.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresEmpresa.setText("Nombre de la empresa");
        consultaIndividualProveedoresEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresTelefono.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresTelefono.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresTelefono.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresTelefono.setText("Numero de telefono");
        consultaIndividualProveedoresTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresCorreo.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresCorreo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresCorreo.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresCorreo.setText("Correo electronico");
        consultaIndividualProveedoresCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresCalle.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresCalle.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresCalle.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresCalle.setText("Calle donde se ubica");
        consultaIndividualProveedoresCalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresNumero.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresNumero.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresNumero.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresNumero.setText("Numero de domicilio");
        consultaIndividualProveedoresNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresColonia.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresColonia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresColonia.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresColonia.setText("Colonia");
        consultaIndividualProveedoresColonia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresEscribirEmpresa.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEscribirEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEscribirEmpresa.setEnabled(false);

        consultaIndividualProveedoresEscribirID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEscribirID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEscribirID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarConsultaIndividualProveedoresID(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarConsultaIndividualProveedoresID(evt);
            }
        });
        consultaIndividualProveedoresEscribirID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarConsultaIndividualProveedoresID(evt);
            }
        });

        consultaIndividualProveedoresEscribirCorreo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEscribirCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEscribirCorreo.setEnabled(false);

        consultaIndividualProveedoresEscribirTelefono.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEscribirTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEscribirTelefono.setEnabled(false);

        consultaIndividualProveedoresEscribirCalle.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEscribirCalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEscribirCalle.setEnabled(false);
        consultaIndividualProveedoresEscribirCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualProveedoresEscribirCalleActionPerformed(evt);
            }
        });

        consultaIndividualProveedoresEscribirNumero.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEscribirNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEscribirNumero.setEnabled(false);

        consultaIndividualProveedoresEscribirColonia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresEscribirColonia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresEscribirColonia.setEnabled(false);

        consultaIndividualProveedoresBotonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresBotonBuscar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        consultaIndividualProveedoresBotonBuscar.setText("Buscar");
        consultaIndividualProveedoresBotonBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresBotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaIndividualProveedoresBotonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaIndividualProveedoresBotonBuscarMouseExited(evt);
            }
        });
        consultaIndividualProveedoresBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualProveedoresBotonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaIndividualProveedoresCuerpoLayout = new javax.swing.GroupLayout(consultaIndividualProveedoresCuerpo);
        consultaIndividualProveedoresCuerpo.setLayout(consultaIndividualProveedoresCuerpoLayout);
        consultaIndividualProveedoresCuerpoLayout.setHorizontalGroup(
            consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualProveedoresCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(consultaIndividualProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(consultaIndividualProveedoresID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaIndividualProveedoresEscribirID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaIndividualProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(consultaIndividualProveedoresColonia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultaIndividualProveedoresEscribirColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaIndividualProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(consultaIndividualProveedoresNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(consultaIndividualProveedoresEscribirNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(consultaIndividualProveedoresCuerpoLayout.createSequentialGroup()
                            .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(consultaIndividualProveedoresCorreo)
                                .addComponent(consultaIndividualProveedoresCalle))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(consultaIndividualProveedoresEscribirCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(consultaIndividualProveedoresEscribirCalle)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaIndividualProveedoresCuerpoLayout.createSequentialGroup()
                            .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(consultaIndividualProveedoresTelefono)
                                .addComponent(consultaIndividualProveedoresEmpresa))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(consultaIndividualProveedoresEscribirEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(consultaIndividualProveedoresEscribirTelefono)))))
                .addGap(18, 18, 18)
                .addComponent(consultaIndividualProveedoresBotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaIndividualProveedoresCuerpoLayout.setVerticalGroup(
            consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualProveedoresCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresID)
                    .addComponent(consultaIndividualProveedoresEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaIndividualProveedoresBotonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresEmpresa)
                    .addComponent(consultaIndividualProveedoresEscribirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresTelefono)
                    .addComponent(consultaIndividualProveedoresEscribirTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresCorreo)
                    .addComponent(consultaIndividualProveedoresEscribirCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresCalle)
                    .addComponent(consultaIndividualProveedoresEscribirCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresNumero)
                    .addComponent(consultaIndividualProveedoresEscribirNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaIndividualProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresColonia)
                    .addComponent(consultaIndividualProveedoresEscribirColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultaIndividualProveedoresPie.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualProveedoresPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualProveedoresBotonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresBotonLimpiar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresBotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        consultaIndividualProveedoresBotonLimpiar.setText("Limpiar");
        consultaIndividualProveedoresBotonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresBotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaIndividualProveedoresBotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaIndividualProveedoresBotonLimpiarMouseExited(evt);
            }
        });
        consultaIndividualProveedoresBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualProveedoresBotonLimpiarActionPerformed(evt);
            }
        });

        consultaIndividualProveedoresBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualProveedoresBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualProveedoresBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        consultaIndividualProveedoresBotonSalir.setText("Salir");
        consultaIndividualProveedoresBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualProveedoresBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaIndividualProveedoresBotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaIndividualProveedoresBotonSalirMouseExited(evt);
            }
        });
        consultaIndividualProveedoresBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualProveedoresBotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaIndividualProveedoresPieLayout = new javax.swing.GroupLayout(consultaIndividualProveedoresPie);
        consultaIndividualProveedoresPie.setLayout(consultaIndividualProveedoresPieLayout);
        consultaIndividualProveedoresPieLayout.setHorizontalGroup(
            consultaIndividualProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualProveedoresPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaIndividualProveedoresBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(consultaIndividualProveedoresBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        consultaIndividualProveedoresPieLayout.setVerticalGroup(
            consultaIndividualProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualProveedoresPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaIndividualProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualProveedoresBotonSalir)
                    .addComponent(consultaIndividualProveedoresBotonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultaIndividualProveedoresPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(consultaIndividualProveedoresEncabezado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultaIndividualProveedoresCuerpo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaIndividualProveedoresEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaIndividualProveedoresCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaIndividualProveedoresPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaIndividualProveedoresEscribirCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresEscribirCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaIndividualProveedoresEscribirCalleActionPerformed

    private void consultaIndividualProveedoresBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonLimpiarActionPerformed
        // TODO add your handling code here:
        consultaIndividualProveedoresEscribirID.setText(null);
        consultaIndividualProveedoresEscribirEmpresa.setText(null);
        consultaIndividualProveedoresEscribirTelefono.setText(null);
        consultaIndividualProveedoresEscribirCorreo.setText(null);
        consultaIndividualProveedoresEscribirCalle.setText(null);
        consultaIndividualProveedoresEscribirNumero.setText(null);
        consultaIndividualProveedoresEscribirColonia.setText(null);
        
        consultaIndividualProveedoresEscribirID.requestFocus();
    }//GEN-LAST:event_consultaIndividualProveedoresBotonLimpiarActionPerformed

    private void consultaIndividualProveedoresBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonBuscarActionPerformed
        // TODO add your handling code here:
        id = consultaIndividualProveedoresEscribirID.getText().toString();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa un ID");
            consultaIndividualProveedoresEscribirID.requestFocus();
        } else {

            try {
                bd = new Conexion();
                s = null;
                s = Conexion.conectar().createStatement();
                queryotro = "select * from proveedores where ID_proveedor='" + id + "';";
                res = bd.resultado(queryotro);

                if (res.next()) {

                    consultaIndividualProveedoresEscribirEmpresa.setText(res.getString("empresa"));
                    consultaIndividualProveedoresEscribirTelefono.setText(res.getString("telefono"));
                    consultaIndividualProveedoresEscribirCorreo.setText(res.getString("correo"));
                    consultaIndividualProveedoresEscribirCalle.setText(res.getString("calle"));
                    consultaIndividualProveedoresEscribirNumero.setText(res.getString("numero"));
                    consultaIndividualProveedoresEscribirColonia.setText(res.getString("colonia"));

                    consultaIndividualProveedoresEscribirID.requestFocus();
                    bd.cerrar();
                } else {

                    JOptionPane.showMessageDialog(null, "el proveedor no existe");
                    consultaIndividualProveedoresEscribirID.setText(null);
                    consultaIndividualProveedoresEscribirID.requestFocus();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
            }
        }
    }//GEN-LAST:event_consultaIndividualProveedoresBotonBuscarActionPerformed

    private void consultaIndividualProveedoresBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonSalirActionPerformed
        // TODO add your handling code here:
        menuProveedores nuevo = new menuProveedores();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_consultaIndividualProveedoresBotonSalirActionPerformed

    private void resaltarConsultaIndividualProveedoresID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarConsultaIndividualProveedoresID
        // TODO add your handling code here:
        consultaIndividualProveedoresID.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualProveedoresEscribirID.setBackground(new Color(0, 0, 196));

    }//GEN-LAST:event_resaltarConsultaIndividualProveedoresID

    private void restaurarConsultaIndividualProveedoresID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarConsultaIndividualProveedoresID
        // TODO add your handling code here:
        consultaIndividualProveedoresID.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualProveedoresEscribirID.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarConsultaIndividualProveedoresID

    private void verificarConsultaIndividualProveedoresID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarConsultaIndividualProveedoresID
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (consultaIndividualProveedoresEscribirID.getText().length() >= 20) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarConsultaIndividualProveedoresID

    private void consultaIndividualProveedoresBotonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonBuscarMouseEntered
        // TODO add your handling code here:
         consultaIndividualProveedoresBotonBuscar.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualProveedoresBotonBuscar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaIndividualProveedoresBotonBuscarMouseEntered

    private void consultaIndividualProveedoresBotonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonBuscarMouseExited
        // TODO add your handling code here:
        consultaIndividualProveedoresBotonBuscar.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualProveedoresBotonBuscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaIndividualProveedoresBotonBuscarMouseExited

    private void consultaIndividualProveedoresBotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonLimpiarMouseEntered
        // TODO add your handling code here:
        consultaIndividualProveedoresBotonLimpiar.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualProveedoresBotonLimpiar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaIndividualProveedoresBotonLimpiarMouseEntered

    private void consultaIndividualProveedoresBotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonLimpiarMouseExited
        // TODO add your handling code here:
        consultaIndividualProveedoresBotonLimpiar.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualProveedoresBotonLimpiar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaIndividualProveedoresBotonLimpiarMouseExited

    private void consultaIndividualProveedoresBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonSalirMouseEntered
        // TODO add your handling code here:
        consultaIndividualProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualProveedoresBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaIndividualProveedoresBotonSalirMouseEntered

    private void consultaIndividualProveedoresBotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualProveedoresBotonSalirMouseExited
        // TODO add your handling code here:
        consultaIndividualProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualProveedoresBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaIndividualProveedoresBotonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaIndividualProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaIndividualProveedoresBotonBuscar;
    private javax.swing.JButton consultaIndividualProveedoresBotonLimpiar;
    private javax.swing.JButton consultaIndividualProveedoresBotonSalir;
    private javax.swing.JLabel consultaIndividualProveedoresCalle;
    private javax.swing.JLabel consultaIndividualProveedoresColonia;
    private javax.swing.JLabel consultaIndividualProveedoresCorreo;
    private javax.swing.JPanel consultaIndividualProveedoresCuerpo;
    private javax.swing.JLabel consultaIndividualProveedoresEmpresa;
    private javax.swing.JPanel consultaIndividualProveedoresEncabezado;
    private javax.swing.JTextField consultaIndividualProveedoresEscribirCalle;
    private javax.swing.JTextField consultaIndividualProveedoresEscribirColonia;
    private javax.swing.JTextField consultaIndividualProveedoresEscribirCorreo;
    private javax.swing.JTextField consultaIndividualProveedoresEscribirEmpresa;
    private javax.swing.JTextField consultaIndividualProveedoresEscribirID;
    private javax.swing.JTextField consultaIndividualProveedoresEscribirNumero;
    private javax.swing.JTextField consultaIndividualProveedoresEscribirTelefono;
    private javax.swing.JLabel consultaIndividualProveedoresID;
    private javax.swing.JLabel consultaIndividualProveedoresNumero;
    private javax.swing.JPanel consultaIndividualProveedoresPie;
    private javax.swing.JLabel consultaIndividualProveedoresTelefono;
    private javax.swing.JLabel consultaIndividualProveedoresTitulo;
    // End of variables declaration//GEN-END:variables
}
