/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class consultaGeneralProveedores extends javax.swing.JFrame {

    String datos[] = new String[7];
    String query;
    Conexion bd;
    Statement s;
    ResultSet res;

    /**
     * Creates new form consultaGeneralProveedores
     */
    public consultaGeneralProveedores() {
        initComponents();
    }
    int bandera = 0;
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaGeneralProveedoresEncabezado = new javax.swing.JPanel();
        consultaGeneralProveedoresTitulo = new javax.swing.JLabel();
        consultaGeneralProveedoresCuerpo = new javax.swing.JPanel();
        consultaGeneralProveedoresScrollPane = new javax.swing.JScrollPane();
        consultaGeneralProveedoresTabla = new javax.swing.JTable();
        consultaGeneralProveedoresPie = new javax.swing.JPanel();
        consultaGeneralProveedoresBotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                activarVentanaConsultaGeneralProveedores(evt);
            }
        });

        consultaGeneralProveedoresEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProveedoresEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaGeneralProveedoresTitulo.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProveedoresTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        consultaGeneralProveedoresTitulo.setForeground(new java.awt.Color(255, 255, 255));
        consultaGeneralProveedoresTitulo.setText("Lista de proveedores");

        javax.swing.GroupLayout consultaGeneralProveedoresEncabezadoLayout = new javax.swing.GroupLayout(consultaGeneralProveedoresEncabezado);
        consultaGeneralProveedoresEncabezado.setLayout(consultaGeneralProveedoresEncabezadoLayout);
        consultaGeneralProveedoresEncabezadoLayout.setHorizontalGroup(
            consultaGeneralProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProveedoresEncabezadoLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(consultaGeneralProveedoresTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaGeneralProveedoresEncabezadoLayout.setVerticalGroup(
            consultaGeneralProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaGeneralProveedoresEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultaGeneralProveedoresTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        consultaGeneralProveedoresCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProveedoresCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaGeneralProveedoresTabla.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProveedoresTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaGeneralProveedoresTabla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        consultaGeneralProveedoresTabla.setForeground(new java.awt.Color(255, 255, 255));
        consultaGeneralProveedoresTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        consultaGeneralProveedoresTabla.setEnabled(false);
        consultaGeneralProveedoresTabla.setGridColor(new java.awt.Color(255, 255, 255));
        consultaGeneralProveedoresScrollPane.setViewportView(consultaGeneralProveedoresTabla);

        javax.swing.GroupLayout consultaGeneralProveedoresCuerpoLayout = new javax.swing.GroupLayout(consultaGeneralProveedoresCuerpo);
        consultaGeneralProveedoresCuerpo.setLayout(consultaGeneralProveedoresCuerpoLayout);
        consultaGeneralProveedoresCuerpoLayout.setHorizontalGroup(
            consultaGeneralProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(consultaGeneralProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultaGeneralProveedoresCuerpoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(consultaGeneralProveedoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        consultaGeneralProveedoresCuerpoLayout.setVerticalGroup(
            consultaGeneralProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
            .addGroup(consultaGeneralProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaGeneralProveedoresCuerpoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaGeneralProveedoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        consultaGeneralProveedoresPie.setBackground(new java.awt.Color(0, 0, 0));
        consultaGeneralProveedoresPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaGeneralProveedoresPie.setForeground(new java.awt.Color(255, 255, 255));

        consultaGeneralProveedoresBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        consultaGeneralProveedoresBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaGeneralProveedoresBotonSalir.setForeground(new java.awt.Color(0, 0, 0));
        consultaGeneralProveedoresBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        consultaGeneralProveedoresBotonSalir.setText("Salir");
        consultaGeneralProveedoresBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaGeneralProveedoresBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaGeneralProveedoresBotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaGeneralProveedoresBotonSalirMouseExited(evt);
            }
        });
        consultaGeneralProveedoresBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaGeneralProveedoresBotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaGeneralProveedoresPieLayout = new javax.swing.GroupLayout(consultaGeneralProveedoresPie);
        consultaGeneralProveedoresPie.setLayout(consultaGeneralProveedoresPieLayout);
        consultaGeneralProveedoresPieLayout.setHorizontalGroup(
            consultaGeneralProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProveedoresPieLayout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(consultaGeneralProveedoresBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaGeneralProveedoresPieLayout.setVerticalGroup(
            consultaGeneralProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaGeneralProveedoresPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaGeneralProveedoresBotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultaGeneralProveedoresEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaGeneralProveedoresCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaGeneralProveedoresPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaGeneralProveedoresEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaGeneralProveedoresCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaGeneralProveedoresPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaGeneralProveedoresBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaGeneralProveedoresBotonSalirActionPerformed
        // TODO add your handling code here:
        menuProveedores nuevo = new menuProveedores();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_consultaGeneralProveedoresBotonSalirActionPerformed

    public void cargarTabla() {
        modelo.addColumn("ID del proveedor");
        modelo.addColumn("Empresa");
        modelo.addColumn("Telefono");
        modelo.addColumn("Correo");
        modelo.addColumn("Calle");
        modelo.addColumn("Numero");
        modelo.addColumn("Colonia");

        consultaGeneralProveedoresTabla.setModel(modelo);

        query = "select * from proveedores";

        try {

            bd = new Conexion();
            s = null;
            s = Conexion.conectar().createStatement();
            res = s.executeQuery(query);
            while (res.next()) {
                datos[0] = res.getString("ID_proveedor");
                datos[1] = res.getString("Empresa");
                datos[2] = res.getString("Telefono");
                datos[3] = res.getString("Correo");
                datos[4] = res.getString("Calle");
                datos[5] = res.getString("Numero");
                datos[6] = res.getString("Colonia");
                modelo.addRow(datos);
            }

            consultaGeneralProveedoresTabla.setModel(modelo);

        } catch (Exception e) {

        }
    }

    private void activarVentanaConsultaGeneralProveedores(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_activarVentanaConsultaGeneralProveedores
        // TODO add your handling code here:
        if (bandera == 0) {
            cargarTabla();
            bandera = 1;
        }
    }//GEN-LAST:event_activarVentanaConsultaGeneralProveedores

    private void consultaGeneralProveedoresBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaGeneralProveedoresBotonSalirMouseEntered
        // TODO add your handling code here:
        consultaGeneralProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaGeneralProveedoresBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaGeneralProveedoresBotonSalirMouseEntered

    private void consultaGeneralProveedoresBotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaGeneralProveedoresBotonSalirMouseExited
        // TODO add your handling code here:
        consultaGeneralProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaGeneralProveedoresBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaGeneralProveedoresBotonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaGeneralProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaGeneralProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaGeneralProveedoresBotonSalir;
    private javax.swing.JPanel consultaGeneralProveedoresCuerpo;
    private javax.swing.JPanel consultaGeneralProveedoresEncabezado;
    private javax.swing.JPanel consultaGeneralProveedoresPie;
    private javax.swing.JScrollPane consultaGeneralProveedoresScrollPane;
    private javax.swing.JTable consultaGeneralProveedoresTabla;
    private javax.swing.JLabel consultaGeneralProveedoresTitulo;
    // End of variables declaration//GEN-END:variables
}
