/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import static Ventanas.registrarCompras.registrarComprasEscribirProveedor;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author David Franco
 */
public class consultaIndividualCompras extends javax.swing.JFrame {

    String id, queryotro;
    Conexion bd;
    Statement s;
    ResultSet res;

    /**
     * Creates new form consultaIndividualCompras
     */
    public consultaIndividualCompras() {
        initComponents();
        consultaIndividualComprasEscribirProveedor.removeAllItems();
    }
    int bandera = 0;
    ArrayList<String> listaProveedores = new ArrayList<String>();
    DefaultComboBoxModel modelo = new DefaultComboBoxModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaIndividualComprasEncabezado = new javax.swing.JPanel();
        consultaIndividualComprasTitulo = new javax.swing.JLabel();
        consultaIndividualComprasCuerpo = new javax.swing.JPanel();
        consultaIndividualComprasID = new javax.swing.JLabel();
        consultaIndividualComprasFecha = new javax.swing.JLabel();
        consultaIndividualComprasCostoTotal = new javax.swing.JLabel();
        consultaIndividualComprasEscribirCostoTotal = new javax.swing.JTextField();
        consultaIndividualComprasEscribirID = new javax.swing.JTextField();
        consultaIndividualComprasEscribirDia = new javax.swing.JComboBox<>();
        consultaIndividualComprasEscribirMes = new javax.swing.JComboBox<>();
        consultaIndividualComprasEscribirAño = new javax.swing.JComboBox<>();
        consultaIndividualComprasBotonBuscar = new javax.swing.JButton();
        registrarComprasProveedor = new javax.swing.JLabel();
        consultaIndividualComprasEscribirProveedor = new javax.swing.JComboBox<>();
        consultaIndividualComprasPie = new javax.swing.JPanel();
        consultaIndividualComprasBotonSalir = new javax.swing.JButton();
        consultaIndividualComprasBotonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                consultaIndividualComprasCargarProveedores(evt);
            }
        });

        consultaIndividualComprasEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        consultaIndividualComprasTitulo.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        consultaIndividualComprasTitulo.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasTitulo.setText("Buscar compras");
        consultaIndividualComprasTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout consultaIndividualComprasEncabezadoLayout = new javax.swing.GroupLayout(consultaIndividualComprasEncabezado);
        consultaIndividualComprasEncabezado.setLayout(consultaIndividualComprasEncabezadoLayout);
        consultaIndividualComprasEncabezadoLayout.setHorizontalGroup(
            consultaIndividualComprasEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualComprasEncabezadoLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(consultaIndividualComprasTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaIndividualComprasEncabezadoLayout.setVerticalGroup(
            consultaIndividualComprasEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualComprasEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultaIndividualComprasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        consultaIndividualComprasCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasCuerpo.setForeground(new java.awt.Color(255, 255, 255));

        consultaIndividualComprasID.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasID.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasID.setText("ID de la compra");

        consultaIndividualComprasFecha.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasFecha.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasFecha.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasFecha.setText("Fecha");

        consultaIndividualComprasCostoTotal.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasCostoTotal.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasCostoTotal.setForeground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasCostoTotal.setText("Total pagado");

        consultaIndividualComprasEscribirCostoTotal.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasEscribirCostoTotal.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasEscribirCostoTotal.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasEscribirCostoTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasEscribirCostoTotal.setEnabled(false);

        consultaIndividualComprasEscribirID.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasEscribirID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasEscribirID.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasEscribirID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasEscribirID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarConsultaIndividualComprasID(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarConsultaIndividualComprasID(evt);
            }
        });

        consultaIndividualComprasEscribirDia.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasEscribirDia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasEscribirDia.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasEscribirDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        consultaIndividualComprasEscribirDia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasEscribirDia.setEnabled(false);
        consultaIndividualComprasEscribirDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualComprasEscribirDiaActionPerformed(evt);
            }
        });

        consultaIndividualComprasEscribirMes.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasEscribirMes.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasEscribirMes.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasEscribirMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        consultaIndividualComprasEscribirMes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasEscribirMes.setEnabled(false);
        consultaIndividualComprasEscribirMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualComprasEscribirMesActionPerformed(evt);
            }
        });

        consultaIndividualComprasEscribirAño.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasEscribirAño.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasEscribirAño.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasEscribirAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        consultaIndividualComprasEscribirAño.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasEscribirAño.setEnabled(false);
        consultaIndividualComprasEscribirAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualComprasEscribirAñoActionPerformed(evt);
            }
        });

        consultaIndividualComprasBotonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasBotonBuscar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasBotonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        consultaIndividualComprasBotonBuscar.setText("Buscar");
        consultaIndividualComprasBotonBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasBotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaIndividualComprasBotonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaIndividualComprasBotonBuscarMouseExited(evt);
            }
        });
        consultaIndividualComprasBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualComprasBotonBuscarActionPerformed(evt);
            }
        });

        registrarComprasProveedor.setBackground(new java.awt.Color(0, 0, 0));
        registrarComprasProveedor.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarComprasProveedor.setForeground(new java.awt.Color(255, 255, 255));
        registrarComprasProveedor.setText("Proveedor");
        registrarComprasProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        consultaIndividualComprasEscribirProveedor.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasEscribirProveedor.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasEscribirProveedor.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasEscribirProveedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasEscribirProveedor.setEnabled(false);
        consultaIndividualComprasEscribirProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                consultaIndividualComprasEscribirProveedorresaltarRegistrarComprasProveedor(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                consultaIndividualComprasEscribirProveedorrestaurarRegistrarComprasProveedor(evt);
            }
        });
        consultaIndividualComprasEscribirProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualComprasEscribirProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaIndividualComprasCuerpoLayout = new javax.swing.GroupLayout(consultaIndividualComprasCuerpo);
        consultaIndividualComprasCuerpo.setLayout(consultaIndividualComprasCuerpoLayout);
        consultaIndividualComprasCuerpoLayout.setHorizontalGroup(
            consultaIndividualComprasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualComprasCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaIndividualComprasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(consultaIndividualComprasCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarComprasProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaIndividualComprasEscribirProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(consultaIndividualComprasCuerpoLayout.createSequentialGroup()
                        .addComponent(consultaIndividualComprasCostoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaIndividualComprasEscribirCostoTotal))
                    .addGroup(consultaIndividualComprasCuerpoLayout.createSequentialGroup()
                        .addComponent(consultaIndividualComprasFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaIndividualComprasEscribirDia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaIndividualComprasEscribirMes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaIndividualComprasEscribirAño, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(consultaIndividualComprasCuerpoLayout.createSequentialGroup()
                        .addComponent(consultaIndividualComprasID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultaIndividualComprasEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultaIndividualComprasBotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaIndividualComprasCuerpoLayout.setVerticalGroup(
            consultaIndividualComprasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualComprasCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaIndividualComprasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualComprasID)
                    .addComponent(consultaIndividualComprasEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaIndividualComprasBotonBuscar))
                .addGap(18, 18, 18)
                .addGroup(consultaIndividualComprasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualComprasFecha)
                    .addComponent(consultaIndividualComprasEscribirDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaIndividualComprasEscribirMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaIndividualComprasEscribirAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(consultaIndividualComprasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarComprasProveedor)
                    .addComponent(consultaIndividualComprasEscribirProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(consultaIndividualComprasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualComprasCostoTotal)
                    .addComponent(consultaIndividualComprasEscribirCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultaIndividualComprasPie.setBackground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasPie.setForeground(new java.awt.Color(255, 255, 255));

        consultaIndividualComprasBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasBotonSalir.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        consultaIndividualComprasBotonSalir.setText("Salir");
        consultaIndividualComprasBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaIndividualComprasBotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaIndividualComprasBotonSalirMouseExited(evt);
            }
        });
        consultaIndividualComprasBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualComprasBotonSalirActionPerformed(evt);
            }
        });

        consultaIndividualComprasBotonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        consultaIndividualComprasBotonLimpiar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        consultaIndividualComprasBotonLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        consultaIndividualComprasBotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        consultaIndividualComprasBotonLimpiar.setText("Limpiar");
        consultaIndividualComprasBotonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultaIndividualComprasBotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaIndividualComprasBotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaIndividualComprasBotonLimpiarMouseExited(evt);
            }
        });
        consultaIndividualComprasBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaIndividualComprasBotonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaIndividualComprasPieLayout = new javax.swing.GroupLayout(consultaIndividualComprasPie);
        consultaIndividualComprasPie.setLayout(consultaIndividualComprasPieLayout);
        consultaIndividualComprasPieLayout.setHorizontalGroup(
            consultaIndividualComprasPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualComprasPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaIndividualComprasBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultaIndividualComprasBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        consultaIndividualComprasPieLayout.setVerticalGroup(
            consultaIndividualComprasPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaIndividualComprasPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaIndividualComprasPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaIndividualComprasBotonSalir)
                    .addComponent(consultaIndividualComprasBotonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultaIndividualComprasEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaIndividualComprasPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultaIndividualComprasCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultaIndividualComprasEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaIndividualComprasCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultaIndividualComprasPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaIndividualComprasEscribirDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualComprasEscribirDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaIndividualComprasEscribirDiaActionPerformed

    private void consultaIndividualComprasEscribirMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualComprasEscribirMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaIndividualComprasEscribirMesActionPerformed

    private void consultaIndividualComprasEscribirAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualComprasEscribirAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaIndividualComprasEscribirAñoActionPerformed

    private void consultaIndividualComprasBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonLimpiarActionPerformed
        // TODO add your handling code here:
        consultaIndividualComprasEscribirID.setText(null);
        consultaIndividualComprasEscribirDia.setSelectedIndex(0);
        consultaIndividualComprasEscribirMes.setSelectedIndex(0);
        consultaIndividualComprasEscribirAño.setSelectedIndex(0);
        consultaIndividualComprasEscribirProveedor.setSelectedIndex(0);
        consultaIndividualComprasEscribirCostoTotal.setText(null);
        consultaIndividualComprasEscribirID.requestFocus();
    }//GEN-LAST:event_consultaIndividualComprasBotonLimpiarActionPerformed

    private void consultaIndividualComprasBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonSalirActionPerformed
        // TODO add your handling code here:
        menuCompras nuevo = new menuCompras();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_consultaIndividualComprasBotonSalirActionPerformed

    private void resaltarConsultaIndividualComprasID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarConsultaIndividualComprasID
        // TODO add your handling code here:
        consultaIndividualComprasID.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualComprasEscribirID.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarConsultaIndividualComprasID

    private void restaurarConsultaIndividualComprasID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarConsultaIndividualComprasID
        // TODO add your handling code here:
        consultaIndividualComprasID.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualComprasEscribirID.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarConsultaIndividualComprasID

    private void consultaIndividualComprasBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonBuscarActionPerformed
        // TODO add your handling code here:
        id = consultaIndividualComprasEscribirID.getText().toString();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa un ID");
            consultaIndividualComprasEscribirID.requestFocus();
        } else {

            try {
                bd = new Conexion();
                s = null;
                s = Conexion.conectar().createStatement();
                queryotro = "select c.dia_compra, c.mes_compra, c.año_compra, p.empresa, c.total from compras c join proveedores p on c.id_proveedor=p.id_proveedor where ID_compra='" + id + "';";
                res = bd.resultado(queryotro);

                if (res.next()) {

                    consultaIndividualComprasEscribirDia.setSelectedItem(res.getString("Dia_compra"));
                    consultaIndividualComprasEscribirMes.setSelectedItem(res.getString("Mes_compra"));
                    consultaIndividualComprasEscribirAño.setSelectedItem(res.getString("Año_compra"));
                    consultaIndividualComprasEscribirProveedor.setSelectedItem(res.getString("empresa"));
                    consultaIndividualComprasEscribirCostoTotal.setText("$" + res.getString("total"));

                    consultaIndividualComprasEscribirID.requestFocus();
                    bd.cerrar();
                } else {

                    JOptionPane.showMessageDialog(null, "la compra no existe");
                    consultaIndividualComprasEscribirID.setText(null);
                    consultaIndividualComprasEscribirID.requestFocus();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
            }
        }

    }//GEN-LAST:event_consultaIndividualComprasBotonBuscarActionPerformed

    private void consultaIndividualComprasEscribirProveedorresaltarRegistrarComprasProveedor(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_consultaIndividualComprasEscribirProveedorresaltarRegistrarComprasProveedor
        // TODO add your handling code here:
        registrarComprasProveedor.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualComprasEscribirProveedor.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaIndividualComprasEscribirProveedorresaltarRegistrarComprasProveedor

    private void consultaIndividualComprasEscribirProveedorrestaurarRegistrarComprasProveedor(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_consultaIndividualComprasEscribirProveedorrestaurarRegistrarComprasProveedor
        // TODO add your handling code here:
        registrarComprasProveedor.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualComprasEscribirProveedor.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaIndividualComprasEscribirProveedorrestaurarRegistrarComprasProveedor

    private void consultaIndividualComprasBotonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonBuscarMouseEntered
        // TODO add your handling code here:
        consultaIndividualComprasBotonBuscar.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualComprasBotonBuscar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaIndividualComprasBotonBuscarMouseEntered

    private void consultaIndividualComprasBotonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonBuscarMouseExited
        // TODO add your handling code here:
        consultaIndividualComprasBotonBuscar.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualComprasBotonBuscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaIndividualComprasBotonBuscarMouseExited

    private void consultaIndividualComprasBotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonLimpiarMouseEntered
        // TODO add your handling code here:
        consultaIndividualComprasBotonLimpiar.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualComprasBotonLimpiar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaIndividualComprasBotonLimpiarMouseEntered

    private void consultaIndividualComprasBotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonLimpiarMouseExited
        // TODO add your handling code here:
        consultaIndividualComprasBotonLimpiar.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualComprasBotonLimpiar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaIndividualComprasBotonLimpiarMouseExited

    private void consultaIndividualComprasBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonSalirMouseEntered
        // TODO add your handling code here:
        consultaIndividualComprasBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        consultaIndividualComprasBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_consultaIndividualComprasBotonSalirMouseEntered

    private void consultaIndividualComprasBotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaIndividualComprasBotonSalirMouseExited
        // TODO add your handling code here:
        consultaIndividualComprasBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        consultaIndividualComprasBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_consultaIndividualComprasBotonSalirMouseExited

    private void consultaIndividualComprasCargarProveedores(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_consultaIndividualComprasCargarProveedores
        // TODO add your handling code here:
        try {
            bd = new Conexion();
            s = null;
            s = Conexion.conectar().createStatement();
            res = s.executeQuery("select * from proveedores");
            while (res.next()) {

                listaProveedores.add(res.getString("empresa"));
               
            }

            if (bandera == 0) {
                consultaIndividualComprasEscribirProveedor.addItem("Elige un proveedor");//posicion 0 de la lista del combo
                for (int i = 0; i <= listaProveedores.size(); i++) {
                    consultaIndividualComprasEscribirProveedor.addItem(listaProveedores.get(i));
                    bandera = 1;
                }
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_consultaIndividualComprasCargarProveedores

    private void consultaIndividualComprasEscribirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaIndividualComprasEscribirProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaIndividualComprasEscribirProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaIndividualCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaIndividualCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaIndividualComprasBotonBuscar;
    private javax.swing.JButton consultaIndividualComprasBotonLimpiar;
    private javax.swing.JButton consultaIndividualComprasBotonSalir;
    private javax.swing.JLabel consultaIndividualComprasCostoTotal;
    private javax.swing.JPanel consultaIndividualComprasCuerpo;
    private javax.swing.JPanel consultaIndividualComprasEncabezado;
    private javax.swing.JComboBox<String> consultaIndividualComprasEscribirAño;
    private javax.swing.JTextField consultaIndividualComprasEscribirCostoTotal;
    private javax.swing.JComboBox<String> consultaIndividualComprasEscribirDia;
    private javax.swing.JTextField consultaIndividualComprasEscribirID;
    private javax.swing.JComboBox<String> consultaIndividualComprasEscribirMes;
    private javax.swing.JComboBox<String> consultaIndividualComprasEscribirProveedor;
    private javax.swing.JLabel consultaIndividualComprasFecha;
    private javax.swing.JLabel consultaIndividualComprasID;
    private javax.swing.JPanel consultaIndividualComprasPie;
    private javax.swing.JLabel consultaIndividualComprasTitulo;
    private javax.swing.JLabel registrarComprasProveedor;
    // End of variables declaration//GEN-END:variables
}
