/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author David Franco
 */
public class eliminarClientes extends javax.swing.JFrame {

    String id, nombre, apellidoPaterno, apellidoMaterno, sexo, queryotro, eliminar;
    Conexion bd;
    Statement s;
    ResultSet res;
    int respuesta;

    /**
     * Creates new form eliminarClientes
     */
    public eliminarClientes() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarClientesEncabezado = new javax.swing.JPanel();
        eliminarClientesTitulo = new javax.swing.JLabel();
        eliminarClientesCuerpo = new javax.swing.JPanel();
        eliminarClientesID = new javax.swing.JLabel();
        eliminarClientesNombre = new javax.swing.JLabel();
        eliminarClientesApellidoPaterno = new javax.swing.JLabel();
        eliminarClientesApellidoMaterno = new javax.swing.JLabel();
        eliminarClientesSexo = new javax.swing.JLabel();
        eliminarClientesEscribirID = new javax.swing.JTextField();
        eliminarClientesEscribirNombre = new javax.swing.JTextField();
        eliminarClientesEscribirApellidoPaterno = new javax.swing.JTextField();
        eliminarClientesEscribirApellidoMaterno = new javax.swing.JTextField();
        eliminarClientesEscribirSexo = new javax.swing.JComboBox<String>();
        eliminarClientesBotonBuscar = new javax.swing.JButton();
        eliminarClientesPie = new javax.swing.JPanel();
        eliminarClientesBotonEliminar = new javax.swing.JButton();
        eliminarClientesBotonSalir = new javax.swing.JButton();
        eliminarClientesBotonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        eliminarClientesEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarClientesTitulo.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        eliminarClientesTitulo.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClientesTitulo.setText("Eliminar clientes");
        eliminarClientesTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout eliminarClientesEncabezadoLayout = new javax.swing.GroupLayout(eliminarClientesEncabezado);
        eliminarClientesEncabezado.setLayout(eliminarClientesEncabezadoLayout);
        eliminarClientesEncabezadoLayout.setHorizontalGroup(
            eliminarClientesEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarClientesEncabezadoLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(eliminarClientesTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarClientesEncabezadoLayout.setVerticalGroup(
            eliminarClientesEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarClientesEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarClientesTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        eliminarClientesCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarClientesID.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesID.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClientesID.setText("ID del cliente");
        eliminarClientesID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarClientesNombre.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesNombre.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesNombre.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClientesNombre.setText("Nombre");
        eliminarClientesNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarClientesApellidoPaterno.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesApellidoPaterno.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClientesApellidoPaterno.setText("Apellido Paterno");
        eliminarClientesApellidoPaterno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarClientesApellidoMaterno.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesApellidoMaterno.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClientesApellidoMaterno.setText("Apellido Materno");
        eliminarClientesApellidoMaterno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarClientesSexo.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesSexo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesSexo.setForeground(new java.awt.Color(255, 255, 255));
        eliminarClientesSexo.setText("Sexo");
        eliminarClientesSexo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarClientesEscribirID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesEscribirID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesEscribirID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarEliminarClientesID(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarEliminarClientesID(evt);
            }
        });
        eliminarClientesEscribirID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarEliminarClientesID(evt);
            }
        });

        eliminarClientesEscribirNombre.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesEscribirNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesEscribirNombre.setEnabled(false);

        eliminarClientesEscribirApellidoPaterno.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesEscribirApellidoPaterno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesEscribirApellidoPaterno.setEnabled(false);

        eliminarClientesEscribirApellidoMaterno.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesEscribirApellidoMaterno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesEscribirApellidoMaterno.setEnabled(false);

        eliminarClientesEscribirSexo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesEscribirSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir el sexo", "Masculino", "Femenino" }));
        eliminarClientesEscribirSexo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesEscribirSexo.setEnabled(false);

        eliminarClientesBotonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        eliminarClientesBotonBuscar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        eliminarClientesBotonBuscar.setText("Buscar");
        eliminarClientesBotonBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesBotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonBuscarMouseExited(evt);
            }
        });
        eliminarClientesBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClientesBotonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarClientesCuerpoLayout = new javax.swing.GroupLayout(eliminarClientesCuerpo);
        eliminarClientesCuerpo.setLayout(eliminarClientesCuerpoLayout);
        eliminarClientesCuerpoLayout.setHorizontalGroup(
            eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarClientesCuerpoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eliminarClientesCuerpoLayout.createSequentialGroup()
                        .addComponent(eliminarClientesSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarClientesEscribirSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eliminarClientesCuerpoLayout.createSequentialGroup()
                        .addComponent(eliminarClientesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarClientesEscribirNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eliminarClientesCuerpoLayout.createSequentialGroup()
                        .addComponent(eliminarClientesID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarClientesEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, eliminarClientesCuerpoLayout.createSequentialGroup()
                        .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarClientesApellidoMaterno)
                            .addComponent(eliminarClientesApellidoPaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarClientesEscribirApellidoPaterno)
                            .addComponent(eliminarClientesEscribirApellidoMaterno))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarClientesBotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarClientesCuerpoLayout.setVerticalGroup(
            eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarClientesCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarClientesID)
                    .addComponent(eliminarClientesEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarClientesBotonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarClientesNombre)
                    .addComponent(eliminarClientesEscribirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarClientesApellidoPaterno)
                    .addComponent(eliminarClientesEscribirApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarClientesApellidoMaterno)
                    .addComponent(eliminarClientesEscribirApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eliminarClientesCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarClientesSexo)
                    .addComponent(eliminarClientesEscribirSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );

        eliminarClientesPie.setBackground(new java.awt.Color(0, 0, 0));
        eliminarClientesPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesPie.setForeground(new java.awt.Color(255, 255, 255));

        eliminarClientesBotonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminarClientesBotonEliminar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesBotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.jpg"))); // NOI18N
        eliminarClientesBotonEliminar.setText("Eliminar");
        eliminarClientesBotonEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesBotonEliminar.setEnabled(false);
        eliminarClientesBotonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonEliminarMouseExited(evt);
            }
        });
        eliminarClientesBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClientesBotonEliminarActionPerformed(evt);
            }
        });

        eliminarClientesBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        eliminarClientesBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        eliminarClientesBotonSalir.setText("Salir");
        eliminarClientesBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonSalirMouseExited(evt);
            }
        });
        eliminarClientesBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClientesBotonSalirActionPerformed(evt);
            }
        });

        eliminarClientesBotonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        eliminarClientesBotonLimpiar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        eliminarClientesBotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        eliminarClientesBotonLimpiar.setText("Limpiar");
        eliminarClientesBotonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarClientesBotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarClientesBotonLimpiarMouseExited(evt);
            }
        });
        eliminarClientesBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClientesBotonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarClientesPieLayout = new javax.swing.GroupLayout(eliminarClientesPie);
        eliminarClientesPie.setLayout(eliminarClientesPieLayout);
        eliminarClientesPieLayout.setHorizontalGroup(
            eliminarClientesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarClientesPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarClientesBotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(eliminarClientesBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminarClientesBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        eliminarClientesPieLayout.setVerticalGroup(
            eliminarClientesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarClientesPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminarClientesPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarClientesBotonSalir)
                    .addComponent(eliminarClientesBotonEliminar)
                    .addComponent(eliminarClientesBotonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminarClientesEncabezado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarClientesPie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eliminarClientesCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarClientesEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarClientesCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarClientesPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarClientesBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClientesBotonLimpiarActionPerformed
        // TODO add your handling code here:
        eliminarClientesEscribirID.setText(null);
        eliminarClientesEscribirNombre.setText(null);
        eliminarClientesEscribirApellidoPaterno.setText(null);
        eliminarClientesEscribirApellidoMaterno.setText(null);
        eliminarClientesEscribirSexo.setSelectedIndex(0);

        eliminarClientesEscribirID.enable(true);
        eliminarClientesEscribirID.requestFocus();
        eliminarClientesBotonEliminar.setEnabled(false);
    }//GEN-LAST:event_eliminarClientesBotonLimpiarActionPerformed

    private void eliminarClientesBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClientesBotonSalirActionPerformed
        // TODO add your handling code here:
        menuClientes nuevo = new menuClientes();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_eliminarClientesBotonSalirActionPerformed

    private void resaltarEliminarClientesID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarEliminarClientesID
        // TODO add your handling code here:
        eliminarClientesID.setFont(new java.awt.Font("javanese Text", 3, 14));
        eliminarClientesEscribirID.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarEliminarClientesID

    private void restaurarEliminarClientesID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarEliminarClientesID
        // TODO add your handling code here:
        eliminarClientesID.setFont(new java.awt.Font("javanese Text", 1, 14));
        eliminarClientesEscribirID.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarEliminarClientesID

    private void eliminarClientesBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClientesBotonBuscarActionPerformed
        // TODO add your handling code here:
        id = eliminarClientesEscribirID.getText().toString();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa un ID");
            eliminarClientesEscribirID.requestFocus();
        } else {

            try {
                bd = new Conexion();
                s = null;
                s = Conexion.conectar().createStatement();
                queryotro = "select * from clientes where ID_cliente='" + id + "';";
                res = bd.resultado(queryotro);

                if (res.next()) {

                    eliminarClientesEscribirID.enable(false);

                    eliminarClientesEscribirNombre.setText(res.getString("nombre"));
                    eliminarClientesEscribirApellidoPaterno.setText(res.getString("apellido_paterno"));
                    eliminarClientesEscribirApellidoMaterno.setText(res.getString("apellido_materno"));
                    eliminarClientesEscribirSexo.setSelectedItem(res.getString("sexo"));

                    eliminarClientesBotonEliminar.setEnabled(true);

                    bd.cerrar();
                } else {

                    JOptionPane.showMessageDialog(null, "el cliente no existe");
                    eliminarClientesEscribirID.setText(null);
                    eliminarClientesEscribirID.requestFocus();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
            }
        }
    }//GEN-LAST:event_eliminarClientesBotonBuscarActionPerformed

    private void eliminarClientesBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClientesBotonEliminarActionPerformed
        // TODO add your handling code here:
        id = eliminarClientesEscribirID.getText().toString();
        nombre = eliminarClientesEscribirNombre.getText().toString();
        apellidoPaterno = eliminarClientesEscribirApellidoPaterno.getText().toString();
        apellidoMaterno = eliminarClientesEscribirApellidoMaterno.getText().toString();
        sexo = eliminarClientesEscribirSexo.getSelectedItem().toString();

        if (id.length() > 0) {
            if (nombre.length() > 2 && apellidoPaterno.length() > 0 && apellidoMaterno.length() > 0 && sexo.length() < 14) {

                try {
                    bd = new Conexion();
                    s = null;
                    s = Conexion.conectar().createStatement();

                    queryotro = "select * from clientes where ID_cliente='" + id + "';";

                    respuesta = JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas eliminar el registro?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (respuesta == JOptionPane.YES_OPTION) {
                        if (!bd.resultado(queryotro).next()) {

                            JOptionPane.showMessageDialog(null, "Este cliente no existe");
                            eliminarClientesEscribirID.setText(null);
                            eliminarClientesEscribirID.requestFocus();
                            bd.cerrar();
                        } else {
                            eliminar = "delete from clientes where ID_CLIENTE='" + id + "';";
                            s.execute(eliminar);

                            JOptionPane.showMessageDialog(null, "Se ah eliminado correctamente");
                            eliminarClientesEscribirID.setText(null);
                            eliminarClientesEscribirNombre.setText(null);
                            eliminarClientesEscribirApellidoPaterno.setText(null);
                            eliminarClientesEscribirApellidoMaterno.setText(null);
                            eliminarClientesEscribirSexo.setSelectedIndex(0);

                            eliminarClientesEscribirID.enable(true);
                            eliminarClientesEscribirID.requestFocus();
                            eliminarClientesBotonEliminar.setEnabled(false);
                        }
                    } else if (respuesta == JOptionPane.NO_OPTION) {
                        id = eliminarClientesEscribirID.getText().toString();
                        nombre = eliminarClientesEscribirNombre.getText().toString();
                        apellidoPaterno = eliminarClientesEscribirApellidoPaterno.getText().toString();
                        apellidoMaterno = eliminarClientesEscribirApellidoMaterno.getText().toString();
                        sexo = eliminarClientesEscribirSexo.getSelectedItem().toString();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Es necesario visualizar todos los campos para eliminar");
                eliminarClientesEscribirID.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor realiza una busqueda");
            eliminarClientesEscribirID.requestFocus();
        }
    }//GEN-LAST:event_eliminarClientesBotonEliminarActionPerformed

    private void verificarEliminarClientesID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarEliminarClientesID
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (eliminarClientesEscribirID.getText().length() >= 20) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarEliminarClientesID

    private void eliminarClientesBotonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonBuscarMouseEntered
        // TODO add your handling code here:
        eliminarClientesBotonBuscar.setFont(new java.awt.Font("javanese Text", 3, 14));
        eliminarClientesBotonBuscar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_eliminarClientesBotonBuscarMouseEntered

    private void eliminarClientesBotonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonBuscarMouseExited
        // TODO add your handling code here:
        eliminarClientesBotonBuscar.setFont(new java.awt.Font("javanese Text", 1, 14));
        eliminarClientesBotonBuscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_eliminarClientesBotonBuscarMouseExited

    private void eliminarClientesBotonEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonEliminarMouseEntered
        // TODO add your handling code here:
        eliminarClientesBotonEliminar.setFont(new java.awt.Font("javanese Text", 3, 14));
        eliminarClientesBotonEliminar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_eliminarClientesBotonEliminarMouseEntered

    private void eliminarClientesBotonEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonEliminarMouseExited
        // TODO add your handling code here:
        eliminarClientesBotonEliminar.setFont(new java.awt.Font("javanese Text", 1, 14));
        eliminarClientesBotonEliminar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_eliminarClientesBotonEliminarMouseExited

    private void eliminarClientesBotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonLimpiarMouseEntered
        // TODO add your handling code here:
        eliminarClientesBotonLimpiar.setFont(new java.awt.Font("javanese Text", 3, 14));
        eliminarClientesBotonLimpiar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_eliminarClientesBotonLimpiarMouseEntered

    private void eliminarClientesBotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonLimpiarMouseExited
        // TODO add your handling code here:
        eliminarClientesBotonLimpiar.setFont(new java.awt.Font("javanese Text", 1, 14));
        eliminarClientesBotonLimpiar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_eliminarClientesBotonLimpiarMouseExited

    private void eliminarClientesBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonSalirMouseEntered
        // TODO add your handling code here:
        eliminarClientesBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        eliminarClientesBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_eliminarClientesBotonSalirMouseEntered

    private void eliminarClientesBotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarClientesBotonSalirMouseExited
        // TODO add your handling code here:
        eliminarClientesBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        eliminarClientesBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_eliminarClientesBotonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminarClientes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eliminarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eliminarClientesApellidoMaterno;
    private javax.swing.JLabel eliminarClientesApellidoPaterno;
    private javax.swing.JButton eliminarClientesBotonBuscar;
    private javax.swing.JButton eliminarClientesBotonEliminar;
    private javax.swing.JButton eliminarClientesBotonLimpiar;
    private javax.swing.JButton eliminarClientesBotonSalir;
    private javax.swing.JPanel eliminarClientesCuerpo;
    private javax.swing.JPanel eliminarClientesEncabezado;
    private javax.swing.JTextField eliminarClientesEscribirApellidoMaterno;
    private javax.swing.JTextField eliminarClientesEscribirApellidoPaterno;
    private javax.swing.JTextField eliminarClientesEscribirID;
    private javax.swing.JTextField eliminarClientesEscribirNombre;
    private javax.swing.JComboBox<String> eliminarClientesEscribirSexo;
    private javax.swing.JLabel eliminarClientesID;
    private javax.swing.JLabel eliminarClientesNombre;
    private javax.swing.JPanel eliminarClientesPie;
    private javax.swing.JLabel eliminarClientesSexo;
    private javax.swing.JLabel eliminarClientesTitulo;
    // End of variables declaration//GEN-END:variables
}
