/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author David Franco
 */
public class modificarProductos extends javax.swing.JFrame {

    String id, nombre, tamaño, tipo, existencia, precioCompra, precioVenta, queryotro, actualizar;
    Conexion bd;
    Statement s;
    ResultSet res;

    /**
     * Creates new form modificarProductos
     */
    public modificarProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarProductosEncabezado = new javax.swing.JPanel();
        modificarProductosTitulo = new javax.swing.JLabel();
        modificarProductosCuerpo = new javax.swing.JPanel();
        modificarProductosID = new javax.swing.JLabel();
        modificarProductosNombre = new javax.swing.JLabel();
        modificarProductosTamaño = new javax.swing.JLabel();
        modificarProductosTipo = new javax.swing.JLabel();
        modificarProductosPrecioCompra = new javax.swing.JLabel();
        modificarProductosCantidadExistencia = new javax.swing.JLabel();
        modificarProductosPrecioVenta = new javax.swing.JLabel();
        modificarProductosEscribirID = new javax.swing.JTextField();
        modificarProductosEscribirNombre = new javax.swing.JTextField();
        modificarProductosEscribirTamaño = new javax.swing.JTextField();
        modificarProductosEscribirTipo = new javax.swing.JTextField();
        modificarProductosEscribirPrecioCompra = new javax.swing.JTextField();
        modificarProductosEscribirCantidadExistencia = new javax.swing.JTextField();
        modificarProductosEscribirPrecioVenta = new javax.swing.JTextField();
        modificarProductosBotonBuscar = new javax.swing.JButton();
        modificarProductosPie = new javax.swing.JPanel();
        modificarProductosBotonGuardar = new javax.swing.JButton();
        modificarProductosBotonSalir = new javax.swing.JButton();
        modificarProductosBotonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        modificarProductosEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosTitulo.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        modificarProductosTitulo.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosTitulo.setText("Modificar productos");
        modificarProductosTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout modificarProductosEncabezadoLayout = new javax.swing.GroupLayout(modificarProductosEncabezado);
        modificarProductosEncabezado.setLayout(modificarProductosEncabezadoLayout);
        modificarProductosEncabezadoLayout.setHorizontalGroup(
            modificarProductosEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductosEncabezadoLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(modificarProductosTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modificarProductosEncabezadoLayout.setVerticalGroup(
            modificarProductosEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductosEncabezadoLayout.createSequentialGroup()
                .addComponent(modificarProductosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        modificarProductosCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosID.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosID.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosID.setText("ID del producto");
        modificarProductosID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosNombre.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosNombre.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosNombre.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosNombre.setText("Nombre del producto");
        modificarProductosNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosTamaño.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosTamaño.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosTamaño.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosTamaño.setText("Tamaño del producto");
        modificarProductosTamaño.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosTipo.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosTipo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosTipo.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosTipo.setText("Tipo de producto");
        modificarProductosTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosPrecioCompra.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosPrecioCompra.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosPrecioCompra.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosPrecioCompra.setText("Precio de compra");
        modificarProductosPrecioCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosCantidadExistencia.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosCantidadExistencia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosCantidadExistencia.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosCantidadExistencia.setText("Cantidad en existencia");
        modificarProductosCantidadExistencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosPrecioVenta.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosPrecioVenta.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosPrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        modificarProductosPrecioVenta.setText("Precio de venta");
        modificarProductosPrecioVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProductosEscribirID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosEscribirID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosEscribirID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProductosID(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProductosID(evt);
            }
        });
        modificarProductosEscribirID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosEscribirIDActionPerformed(evt);
            }
        });
        modificarProductosEscribirID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProductosID(evt);
            }
        });

        modificarProductosEscribirNombre.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosEscribirNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosEscribirNombre.setEnabled(false);
        modificarProductosEscribirNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProductosNombre(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProductosNombre(evt);
            }
        });
        modificarProductosEscribirNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosEscribirNombreActionPerformed(evt);
            }
        });
        modificarProductosEscribirNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProductosNombre(evt);
            }
        });

        modificarProductosEscribirTamaño.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosEscribirTamaño.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosEscribirTamaño.setEnabled(false);
        modificarProductosEscribirTamaño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProductosTamaño(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProductosTamaño(evt);
            }
        });
        modificarProductosEscribirTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosEscribirTamañoActionPerformed(evt);
            }
        });
        modificarProductosEscribirTamaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProductosTamaño(evt);
            }
        });

        modificarProductosEscribirTipo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosEscribirTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosEscribirTipo.setEnabled(false);
        modificarProductosEscribirTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProductosTipo(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProductosTipo(evt);
            }
        });
        modificarProductosEscribirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosEscribirTipoActionPerformed(evt);
            }
        });
        modificarProductosEscribirTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProductosTipo(evt);
            }
        });

        modificarProductosEscribirPrecioCompra.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosEscribirPrecioCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosEscribirPrecioCompra.setEnabled(false);
        modificarProductosEscribirPrecioCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProductosPrecioCompra(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProductosPrecioCompra(evt);
            }
        });
        modificarProductosEscribirPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosEscribirPrecioCompraActionPerformed(evt);
            }
        });
        modificarProductosEscribirPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProductosPrecioCompra(evt);
            }
        });

        modificarProductosEscribirCantidadExistencia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosEscribirCantidadExistencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosEscribirCantidadExistencia.setEnabled(false);
        modificarProductosEscribirCantidadExistencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProductosCantidadExistencia(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProductosCantidadExistencia(evt);
            }
        });
        modificarProductosEscribirCantidadExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosEscribirCantidadExistenciaActionPerformed(evt);
            }
        });
        modificarProductosEscribirCantidadExistencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProductosCantidadExistencia(evt);
            }
        });

        modificarProductosEscribirPrecioVenta.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosEscribirPrecioVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosEscribirPrecioVenta.setEnabled(false);
        modificarProductosEscribirPrecioVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProductosPrecioVenta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProductosPrecioVenta(evt);
            }
        });
        modificarProductosEscribirPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosEscribirPrecioVentaActionPerformed(evt);
            }
        });
        modificarProductosEscribirPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProductosPrecioVenta(evt);
            }
        });

        modificarProductosBotonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        modificarProductosBotonBuscar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        modificarProductosBotonBuscar.setText("Buscar");
        modificarProductosBotonBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosBotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resaltarModificarProductosBotonBuscar(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaurarModificarProductosBotonBuscar(evt);
            }
        });
        modificarProductosBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosBotonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarProductosCuerpoLayout = new javax.swing.GroupLayout(modificarProductosCuerpo);
        modificarProductosCuerpo.setLayout(modificarProductosCuerpoLayout);
        modificarProductosCuerpoLayout.setHorizontalGroup(
            modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductosCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarProductosCuerpoLayout.createSequentialGroup()
                        .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(modificarProductosCuerpoLayout.createSequentialGroup()
                                .addComponent(modificarProductosTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modificarProductosEscribirTipo))
                            .addComponent(modificarProductosID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(modificarProductosCuerpoLayout.createSequentialGroup()
                                .addComponent(modificarProductosPrecioVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modificarProductosEscribirPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modificarProductosCuerpoLayout.createSequentialGroup()
                                .addComponent(modificarProductosCantidadExistencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modificarProductosEscribirCantidadExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modificarProductosCuerpoLayout.createSequentialGroup()
                                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(modificarProductosTamaño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modificarProductosNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modificarProductosEscribirNombre)
                                    .addComponent(modificarProductosEscribirTamaño)))
                            .addComponent(modificarProductosPrecioCompra))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarProductosCuerpoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificarProductosEscribirID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificarProductosEscribirPrecioCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarProductosBotonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        modificarProductosCuerpoLayout.setVerticalGroup(
            modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductosCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosID)
                    .addComponent(modificarProductosEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarProductosBotonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosNombre)
                    .addComponent(modificarProductosEscribirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosTamaño)
                    .addComponent(modificarProductosEscribirTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosTipo)
                    .addComponent(modificarProductosEscribirTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosCantidadExistencia)
                    .addComponent(modificarProductosEscribirCantidadExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosPrecioCompra)
                    .addComponent(modificarProductosEscribirPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProductosCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosPrecioVenta)
                    .addComponent(modificarProductosEscribirPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        modificarProductosPie.setBackground(new java.awt.Color(0, 0, 0));
        modificarProductosPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosPie.setForeground(new java.awt.Color(255, 255, 255));

        modificarProductosBotonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        modificarProductosBotonGuardar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.jpg"))); // NOI18N
        modificarProductosBotonGuardar.setText("Guardar");
        modificarProductosBotonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosBotonGuardar.setEnabled(false);
        modificarProductosBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resaltarModificarProductosBotonGuardar(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaurarModificarProductosBotonGuardar(evt);
            }
        });
        modificarProductosBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosBotonGuardarActionPerformed(evt);
            }
        });

        modificarProductosBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        modificarProductosBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        modificarProductosBotonSalir.setText("Salir");
        modificarProductosBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resaltarModificarProductosBotonSalir(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaurarModificarProductosBotonSalir(evt);
            }
        });
        modificarProductosBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosBotonSalirActionPerformed(evt);
            }
        });

        modificarProductosBotonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        modificarProductosBotonLimpiar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProductosBotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        modificarProductosBotonLimpiar.setText("Limpiar");
        modificarProductosBotonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProductosBotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarProductosBotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaurarModificarProductosBotonLimpiar(evt);
            }
        });
        modificarProductosBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductosBotonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarProductosPieLayout = new javax.swing.GroupLayout(modificarProductosPie);
        modificarProductosPie.setLayout(modificarProductosPieLayout);
        modificarProductosPieLayout.setHorizontalGroup(
            modificarProductosPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductosPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarProductosBotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificarProductosBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(modificarProductosBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        modificarProductosPieLayout.setVerticalGroup(
            modificarProductosPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProductosPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarProductosPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProductosBotonSalir)
                    .addComponent(modificarProductosBotonGuardar)
                    .addComponent(modificarProductosBotonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modificarProductosPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarProductosEncabezado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarProductosCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarProductosEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarProductosCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarProductosPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarProductosEscribirIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosEscribirIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductosEscribirIDActionPerformed

    private void modificarProductosEscribirNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosEscribirNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductosEscribirNombreActionPerformed

    private void modificarProductosEscribirTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosEscribirTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductosEscribirTamañoActionPerformed

    private void modificarProductosEscribirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosEscribirTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductosEscribirTipoActionPerformed

    private void modificarProductosEscribirPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosEscribirPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductosEscribirPrecioCompraActionPerformed

    private void modificarProductosEscribirCantidadExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosEscribirCantidadExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductosEscribirCantidadExistenciaActionPerformed

    private void modificarProductosEscribirPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosEscribirPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProductosEscribirPrecioVentaActionPerformed

    private void modificarProductosBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosBotonGuardarActionPerformed
        // TODO add your handling code here:
        id = modificarProductosEscribirID.getText().toString();
        nombre = modificarProductosEscribirNombre.getText().toString();
        tamaño = modificarProductosEscribirTamaño.getText().toString();
        tipo = modificarProductosEscribirTipo.getText().toString();
        existencia = modificarProductosEscribirCantidadExistencia.getText().toString();
        precioCompra = modificarProductosEscribirPrecioCompra.getText().toString();
        precioVenta = modificarProductosEscribirPrecioVenta.getText().toString();

        if (id.length() > 0) {
            if (nombre.length() > 2) {
                if (tamaño.length() > 0) {
                    if (tipo.length() > 0) {
                        if (existencia.length() > 0) {
                            if (precioCompra.length() > 0) {
                                if (precioVenta.length() > 0) {

                                    try {
                                        bd = new Conexion();
                                        s = null;
                                        s = Conexion.conectar().createStatement();

                                        queryotro = "select * from productos_existencia where ID_producto='" + id + "';";
                                        if (!bd.resultado(queryotro).next()) {

                                            JOptionPane.showMessageDialog(null, "Este producto no existe");
                                            modificarProductosEscribirID.setText(null);
                                            modificarProductosEscribirID.requestFocus();
                                            bd.cerrar();
                                        } else {
                                            actualizar = "UPDATE productos_existencia SET NOMBRE='" + nombre + "', TAMAÑO='" + tamaño + "', TIPO='"
                                                    + tipo + "', EXISTENCIA='" + existencia + "',  PRECIO_COMPRA='" + precioCompra + "', PRECIO_VENTA='" + precioVenta + "', DESCRIPCION='" + nombre + " " + tipo + " " + tamaño +"' WHERE ID_PRODUCTO='" + id + "';";
                                            s.execute(actualizar);

                                            JOptionPane.showMessageDialog(null, "Se ah modificado correctamente");

                                            modificarProductosEscribirID.enable(true);
                                            modificarProductosEscribirNombre.enable(false);
                                            modificarProductosEscribirTamaño.enable(false);
                                            modificarProductosEscribirTipo.enable(false);
                                            modificarProductosEscribirCantidadExistencia.enable(false);
                                            modificarProductosEscribirPrecioCompra.enable(false);
                                            modificarProductosEscribirPrecioVenta.enable(false);

                                            modificarProductosEscribirID.setText(null);
                                            modificarProductosEscribirNombre.setText(null);
                                            modificarProductosEscribirTamaño.setText(null);
                                            modificarProductosEscribirTipo.setText(null);
                                            modificarProductosEscribirCantidadExistencia.setText(null);
                                            modificarProductosEscribirPrecioCompra.setText(null);
                                            modificarProductosEscribirPrecioVenta.setText(null);
                                            modificarProductosEscribirID.requestFocus();

                                            modificarProductosBotonGuardar.setEnabled(false);
                                        }
                                    } catch (SQLException e) {
                                        JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                                    modificarProductosEscribirPrecioVenta.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                                modificarProductosEscribirPrecioCompra.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                            modificarProductosEscribirCantidadExistencia.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                        modificarProductosEscribirTipo.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                    modificarProductosEscribirTamaño.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                modificarProductosEscribirNombre.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor realiza una busqueda");
            modificarProductosEscribirID.requestFocus();
        }
    }//GEN-LAST:event_modificarProductosBotonGuardarActionPerformed

    private void modificarProductosBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosBotonLimpiarActionPerformed
        // TODO add your handling code here:
        modificarProductosEscribirID.setText(null);
        modificarProductosEscribirNombre.setText(null);
        modificarProductosEscribirTamaño.setText(null);
        modificarProductosEscribirTipo.setText(null);
        modificarProductosEscribirCantidadExistencia.setText(null);
        modificarProductosEscribirPrecioCompra.setText(null);
        modificarProductosEscribirPrecioVenta.setText(null);

        modificarProductosEscribirID.enable(true);
        modificarProductosEscribirNombre.enable(false);
        modificarProductosEscribirTamaño.enable(false);
        modificarProductosEscribirTipo.enable(false);
        modificarProductosEscribirCantidadExistencia.enable(false);
        modificarProductosEscribirPrecioCompra.enable(false);
        modificarProductosEscribirPrecioVenta.enable(false);

        modificarProductosEscribirID.requestFocus();
        modificarProductosBotonGuardar.setEnabled(false);
    }//GEN-LAST:event_modificarProductosBotonLimpiarActionPerformed

    private void modificarProductosBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosBotonSalirActionPerformed
        // TODO add your handling code here:
        menuProductos nuevo = new menuProductos();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_modificarProductosBotonSalirActionPerformed

    private void resaltarModificarProductosID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProductosID
        // TODO add your handling code here:
        modificarProductosID.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosEscribirID.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosID

    private void restaurarModificarProductosID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProductosID
        // TODO add your handling code here:
        modificarProductosID.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosEscribirID.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosID

    private void resaltarModificarProductosNombre(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProductosNombre
        // TODO add your handling code here:
        modificarProductosNombre.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosEscribirNombre.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosNombre

    private void restaurarModificarProductosNombre(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProductosNombre
        // TODO add your handling code here:
        modificarProductosNombre.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosEscribirNombre.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosNombre

    private void resaltarModificarProductosTamaño(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProductosTamaño
        // TODO add your handling code here:
        modificarProductosTamaño.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosEscribirTamaño.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosTamaño

    private void restaurarModificarProductosTamaño(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProductosTamaño
        // TODO add your handling code here:
        modificarProductosTamaño.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosEscribirTamaño.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosTamaño

    private void resaltarModificarProductosTipo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProductosTipo
        // TODO add your handling code here:
        modificarProductosTipo.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosEscribirTipo.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosTipo

    private void restaurarModificarProductosTipo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProductosTipo
        // TODO add your handling code here:
        modificarProductosTipo.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosEscribirTipo.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosTipo

    private void resaltarModificarProductosCantidadExistencia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProductosCantidadExistencia
        // TODO add your handling code here:
        modificarProductosCantidadExistencia.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosEscribirCantidadExistencia.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosCantidadExistencia

    private void restaurarModificarProductosCantidadExistencia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProductosCantidadExistencia
        // TODO add your handling code here:
        modificarProductosCantidadExistencia.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosEscribirCantidadExistencia.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosCantidadExistencia

    private void resaltarModificarProductosPrecioCompra(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProductosPrecioCompra
        // TODO add your handling code here:
        modificarProductosPrecioCompra.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosEscribirPrecioCompra.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosPrecioCompra

    private void restaurarModificarProductosPrecioCompra(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProductosPrecioCompra
        // TODO add your handling code here:
        modificarProductosPrecioCompra.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosEscribirPrecioCompra.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosPrecioCompra

    private void resaltarModificarProductosPrecioVenta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProductosPrecioVenta
        // TODO add your handling code here:
        modificarProductosPrecioVenta.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosEscribirPrecioVenta.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosPrecioVenta

    private void restaurarModificarProductosPrecioVenta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProductosPrecioVenta
        // TODO add your handling code here:
        modificarProductosPrecioVenta.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosEscribirPrecioVenta.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosPrecioVenta

    private void modificarProductosBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductosBotonBuscarActionPerformed
        // TODO add your handling code here:
        id = modificarProductosEscribirID.getText().toString();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa un ID");
            modificarProductosEscribirID.requestFocus();
        } else {
            try {
                bd = new Conexion();
                s = null;
                s = Conexion.conectar().createStatement();
                queryotro = "select * from productos_existencia where ID_producto='" + id + "';";
                res = bd.resultado(queryotro);

                if (res.next()) {

                    modificarProductosEscribirID.enable(false);
                    modificarProductosEscribirNombre.enable(true);
                    modificarProductosEscribirTamaño.enable(true);
                    modificarProductosEscribirTipo.enable(true);
                    modificarProductosEscribirCantidadExistencia.enable(true);
                    modificarProductosEscribirPrecioCompra.enable(true);
                    modificarProductosEscribirPrecioVenta.enable(true);

                    modificarProductosEscribirNombre.setText(res.getString("nombre"));
                    modificarProductosEscribirTamaño.setText(res.getString("tamaño"));
                    modificarProductosEscribirTipo.setText(res.getString("tipo"));
                    modificarProductosEscribirCantidadExistencia.setText(res.getString("existencia"));
                    modificarProductosEscribirPrecioCompra.setText(res.getString("precio_Compra"));
                    modificarProductosEscribirPrecioVenta.setText(res.getString("precio_Venta"));

                    modificarProductosEscribirNombre.requestFocus();
                    modificarProductosBotonGuardar.setEnabled(true);
                    bd.cerrar();
                } else {

                    JOptionPane.showMessageDialog(null, "el producto no existe");
                    modificarProductosEscribirID.setText(null);
                    modificarProductosEscribirID.requestFocus();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
            }
        }
    }//GEN-LAST:event_modificarProductosBotonBuscarActionPerformed

    private void verificarModificarProductosID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProductosID
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (modificarProductosEscribirID.getText().length() >= 20) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProductosID

    private void verificarModificarProductosNombre(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProductosNombre
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != '-') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();

        } else if (modificarProductosEscribirNombre.getText().length() >= 30) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProductosNombre

    private void verificarModificarProductosTamaño(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProductosTamaño
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C') && (caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != '.') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (modificarProductosEscribirTamaño.getText().length() >= 30) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProductosTamaño

    private void verificarModificarProductosTipo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProductosTipo
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (modificarProductosEscribirTipo.getText().length() >= 50) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProductosTipo

    private void verificarModificarProductosCantidadExistencia(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProductosCantidadExistencia
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (modificarProductosEscribirCantidadExistencia.getText().length() >= 9) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProductosCantidadExistencia

    private void verificarModificarProductosPrecioCompra(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProductosPrecioCompra
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C') && (caracter != '.')) {
            evt.consume();
        } else if (modificarProductosEscribirPrecioCompra.getText().length() >= 9) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProductosPrecioCompra

    private void verificarModificarProductosPrecioVenta(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProductosPrecioVenta
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C') && (caracter != '.')) {

            evt.consume();
        } else if (modificarProductosEscribirPrecioVenta.getText().length() >= 9) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProductosPrecioVenta

    private void resaltarModificarProductosBotonBuscar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resaltarModificarProductosBotonBuscar
        // TODO add your handling code here:
        modificarProductosBotonBuscar.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosBotonBuscar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosBotonBuscar

    private void restaurarModificarProductosBotonBuscar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurarModificarProductosBotonBuscar
        // TODO add your handling code here:
        modificarProductosBotonBuscar.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosBotonBuscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosBotonBuscar

    private void resaltarModificarProductosBotonGuardar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resaltarModificarProductosBotonGuardar
        // TODO add your handling code here:
       
        modificarProductosBotonGuardar.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosBotonGuardar.setBackground(new Color(0, 0, 196));
        
    }//GEN-LAST:event_resaltarModificarProductosBotonGuardar

    private void restaurarModificarProductosBotonGuardar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurarModificarProductosBotonGuardar
        // TODO add your handling code here:
        modificarProductosBotonGuardar.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosBotonGuardar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosBotonGuardar

    private void modificarProductosBotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProductosBotonLimpiarMouseEntered
        // TODO add your handling code here:
        modificarProductosBotonLimpiar.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosBotonLimpiar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_modificarProductosBotonLimpiarMouseEntered

    private void restaurarModificarProductosBotonLimpiar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurarModificarProductosBotonLimpiar
        // TODO add your handling code here:
        modificarProductosBotonLimpiar.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosBotonLimpiar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosBotonLimpiar

    private void resaltarModificarProductosBotonSalir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resaltarModificarProductosBotonSalir
        // TODO add your handling code here:
        modificarProductosBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProductosBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProductosBotonSalir

    private void restaurarModificarProductosBotonSalir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurarModificarProductosBotonSalir
        // TODO add your handling code here:
        modificarProductosBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProductosBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProductosBotonSalir

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton modificarProductosBotonBuscar;
    private javax.swing.JButton modificarProductosBotonGuardar;
    private javax.swing.JButton modificarProductosBotonLimpiar;
    private javax.swing.JButton modificarProductosBotonSalir;
    private javax.swing.JLabel modificarProductosCantidadExistencia;
    private javax.swing.JPanel modificarProductosCuerpo;
    private javax.swing.JPanel modificarProductosEncabezado;
    private javax.swing.JTextField modificarProductosEscribirCantidadExistencia;
    private javax.swing.JTextField modificarProductosEscribirID;
    private javax.swing.JTextField modificarProductosEscribirNombre;
    private javax.swing.JTextField modificarProductosEscribirPrecioCompra;
    private javax.swing.JTextField modificarProductosEscribirPrecioVenta;
    private javax.swing.JTextField modificarProductosEscribirTamaño;
    private javax.swing.JTextField modificarProductosEscribirTipo;
    private javax.swing.JLabel modificarProductosID;
    private javax.swing.JLabel modificarProductosNombre;
    private javax.swing.JPanel modificarProductosPie;
    private javax.swing.JLabel modificarProductosPrecioCompra;
    private javax.swing.JLabel modificarProductosPrecioVenta;
    private javax.swing.JLabel modificarProductosTamaño;
    private javax.swing.JLabel modificarProductosTipo;
    private javax.swing.JLabel modificarProductosTitulo;
    // End of variables declaration//GEN-END:variables
}
