/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author David Franco
 */
public class modificarProveedores extends javax.swing.JFrame {

    String id, empresa, telefono, correo, calle, numero, colonia, queryotro, actualizar;
    Conexion bd;
    Statement s;
    ResultSet res;

    /**
     * Creates new form modificarProveedores
     */
    public modificarProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarProveedoresEncabezado = new javax.swing.JPanel();
        modificarProveedoresTitulo = new javax.swing.JLabel();
        modificarProveedoresCuerpo = new javax.swing.JPanel();
        modificarProveedoresID = new javax.swing.JLabel();
        modificarProveedoresEmpresa = new javax.swing.JLabel();
        modificarProveedoresTelefono = new javax.swing.JLabel();
        modificarProveedoresCorreo = new javax.swing.JLabel();
        modificarProveedoresCalle = new javax.swing.JLabel();
        modificarProveedoresNumero = new javax.swing.JLabel();
        modificarProveedoresColonia = new javax.swing.JLabel();
        modificarProveedoresEscribirEmpresa = new javax.swing.JTextField();
        modificarProveedoresEscribirID = new javax.swing.JTextField();
        modificarProveedoresEscribirCorreo = new javax.swing.JTextField();
        modificarProveedoresEscribirTelefono = new javax.swing.JTextField();
        modificarProveedoresEscribirCalle = new javax.swing.JTextField();
        modificarProveedoresEscribirNumero = new javax.swing.JTextField();
        modificarProveedoresEscribirColonia = new javax.swing.JTextField();
        modificarProveedoresBotonBuscar = new javax.swing.JButton();
        modificarProveedoresPie = new javax.swing.JPanel();
        modificarProveedoresBotonGuardar = new javax.swing.JButton();
        modificarProveedoresBotonLimpiar = new javax.swing.JButton();
        modificarProveedoresBotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        modificarProveedoresEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        modificarProveedoresTitulo.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresTitulo.setFont(new java.awt.Font("Javanese Text", 1, 24)); // NOI18N
        modificarProveedoresTitulo.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresTitulo.setText("Modificar proveedores");
        modificarProveedoresTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout modificarProveedoresEncabezadoLayout = new javax.swing.GroupLayout(modificarProveedoresEncabezado);
        modificarProveedoresEncabezado.setLayout(modificarProveedoresEncabezadoLayout);
        modificarProveedoresEncabezadoLayout.setHorizontalGroup(
            modificarProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarProveedoresEncabezadoLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(modificarProveedoresTitulo)
                .addGap(133, 133, 133))
        );
        modificarProveedoresEncabezadoLayout.setVerticalGroup(
            modificarProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarProveedoresEncabezadoLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(modificarProveedoresTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        modificarProveedoresCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresCuerpo.setForeground(new java.awt.Color(255, 255, 255));

        modificarProveedoresID.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresID.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresID.setText("ID del proveedor");
        modificarProveedoresID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProveedoresEmpresa.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresEmpresa.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEmpresa.setText("Nombre de la empresa");
        modificarProveedoresEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProveedoresTelefono.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresTelefono.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresTelefono.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresTelefono.setText("Numero de telefono");
        modificarProveedoresTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProveedoresCorreo.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresCorreo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresCorreo.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresCorreo.setText("Correo electronico");
        modificarProveedoresCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProveedoresCalle.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresCalle.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresCalle.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresCalle.setText("Calle donde se ubica");
        modificarProveedoresCalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProveedoresNumero.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresNumero.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresNumero.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresNumero.setText("Numero de domicilio");
        modificarProveedoresNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProveedoresColonia.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresColonia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresColonia.setForeground(new java.awt.Color(255, 255, 255));
        modificarProveedoresColonia.setText("Colonia");
        modificarProveedoresColonia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        modificarProveedoresEscribirEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEscribirEmpresa.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEscribirEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEscribirEmpresa.setEnabled(false);
        modificarProveedoresEscribirEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProveedoresEmpresa(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProveedoresEmpresa(evt);
            }
        });
        modificarProveedoresEscribirEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProveedoresEmpresa(evt);
            }
        });

        modificarProveedoresEscribirID.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEscribirID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEscribirID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEscribirID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProveedoresID(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProveedoresID(evt);
            }
        });
        modificarProveedoresEscribirID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProveedoresID(evt);
            }
        });

        modificarProveedoresEscribirCorreo.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEscribirCorreo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEscribirCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEscribirCorreo.setEnabled(false);
        modificarProveedoresEscribirCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProveedoresCorreo(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProveedoresCorreo(evt);
            }
        });
        modificarProveedoresEscribirCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProveedoresCorreo(evt);
            }
        });

        modificarProveedoresEscribirTelefono.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEscribirTelefono.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEscribirTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEscribirTelefono.setEnabled(false);
        modificarProveedoresEscribirTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProveedoresTelefono(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProveedoresTelefono(evt);
            }
        });
        modificarProveedoresEscribirTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedoresEscribirTelefonoActionPerformed(evt);
            }
        });
        modificarProveedoresEscribirTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProveedoresTelefono(evt);
            }
        });

        modificarProveedoresEscribirCalle.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEscribirCalle.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEscribirCalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEscribirCalle.setEnabled(false);
        modificarProveedoresEscribirCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProveedoresCalle(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProveedoresCalle(evt);
            }
        });
        modificarProveedoresEscribirCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedoresEscribirCalleActionPerformed(evt);
            }
        });
        modificarProveedoresEscribirCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProveedoresCalle(evt);
            }
        });

        modificarProveedoresEscribirNumero.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEscribirNumero.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEscribirNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEscribirNumero.setEnabled(false);
        modificarProveedoresEscribirNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProveedoresNumero(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProveedoresNumero(evt);
            }
        });
        modificarProveedoresEscribirNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProveedoresNumero(evt);
            }
        });

        modificarProveedoresEscribirColonia.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresEscribirColonia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresEscribirColonia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresEscribirColonia.setEnabled(false);
        modificarProveedoresEscribirColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarModificarProveedoresColonia(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarModificarProveedoresColonia(evt);
            }
        });
        modificarProveedoresEscribirColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarModificarProveedoresColonia(evt);
            }
        });

        modificarProveedoresBotonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresBotonBuscar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresBotonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        modificarProveedoresBotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.jpg"))); // NOI18N
        modificarProveedoresBotonBuscar.setText("Buscar");
        modificarProveedoresBotonBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresBotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonBuscarMouseExited(evt);
            }
        });
        modificarProveedoresBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedoresBotonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarProveedoresCuerpoLayout = new javax.swing.GroupLayout(modificarProveedoresCuerpo);
        modificarProveedoresCuerpo.setLayout(modificarProveedoresCuerpoLayout);
        modificarProveedoresCuerpoLayout.setHorizontalGroup(
            modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProveedoresCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(modificarProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(modificarProveedoresColonia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificarProveedoresEscribirColonia))
                    .addGroup(modificarProveedoresCuerpoLayout.createSequentialGroup()
                        .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificarProveedoresCorreo)
                            .addComponent(modificarProveedoresCalle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modificarProveedoresEscribirCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(modificarProveedoresEscribirCalle)))
                    .addGroup(modificarProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(modificarProveedoresNumero)
                        .addGap(18, 18, 18)
                        .addComponent(modificarProveedoresEscribirNumero))
                    .addGroup(modificarProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(modificarProveedoresID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificarProveedoresEscribirID))
                    .addGroup(modificarProveedoresCuerpoLayout.createSequentialGroup()
                        .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificarProveedoresTelefono)
                            .addComponent(modificarProveedoresEmpresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modificarProveedoresEscribirTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(modificarProveedoresEscribirEmpresa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarProveedoresBotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        modificarProveedoresCuerpoLayout.setVerticalGroup(
            modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProveedoresCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresID)
                    .addComponent(modificarProveedoresEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarProveedoresBotonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresEmpresa)
                    .addComponent(modificarProveedoresEscribirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresTelefono)
                    .addComponent(modificarProveedoresEscribirTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresCorreo)
                    .addComponent(modificarProveedoresEscribirCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresCalle)
                    .addComponent(modificarProveedoresEscribirCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresNumero)
                    .addComponent(modificarProveedoresEscribirNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modificarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresColonia)
                    .addComponent(modificarProveedoresEscribirColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        modificarProveedoresPie.setBackground(new java.awt.Color(0, 0, 0));
        modificarProveedoresPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresPie.setForeground(new java.awt.Color(0, 0, 0));

        modificarProveedoresBotonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresBotonGuardar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresBotonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        modificarProveedoresBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.jpg"))); // NOI18N
        modificarProveedoresBotonGuardar.setText("Guardar");
        modificarProveedoresBotonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresBotonGuardar.setEnabled(false);
        modificarProveedoresBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonGuardarMouseExited(evt);
            }
        });
        modificarProveedoresBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedoresBotonGuardarActionPerformed(evt);
            }
        });

        modificarProveedoresBotonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresBotonLimpiar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresBotonLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        modificarProveedoresBotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        modificarProveedoresBotonLimpiar.setText("Limpiar");
        modificarProveedoresBotonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresBotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonLimpiarMouseExited(evt);
            }
        });
        modificarProveedoresBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedoresBotonLimpiarActionPerformed(evt);
            }
        });

        modificarProveedoresBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        modificarProveedoresBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        modificarProveedoresBotonSalir.setForeground(new java.awt.Color(0, 0, 0));
        modificarProveedoresBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        modificarProveedoresBotonSalir.setText("Salir");
        modificarProveedoresBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarProveedoresBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarProveedoresBotonSalirMouseExited(evt);
            }
        });
        modificarProveedoresBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedoresBotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarProveedoresPieLayout = new javax.swing.GroupLayout(modificarProveedoresPie);
        modificarProveedoresPie.setLayout(modificarProveedoresPieLayout);
        modificarProveedoresPieLayout.setHorizontalGroup(
            modificarProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProveedoresPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarProveedoresBotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(modificarProveedoresBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(modificarProveedoresBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        modificarProveedoresPieLayout.setVerticalGroup(
            modificarProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarProveedoresPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarProveedoresBotonGuardar)
                    .addComponent(modificarProveedoresBotonSalir)
                    .addComponent(modificarProveedoresBotonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(modificarProveedoresPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarProveedoresEncabezado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarProveedoresCuerpo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modificarProveedoresEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarProveedoresCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarProveedoresPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarProveedoresEscribirCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedoresEscribirCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProveedoresEscribirCalleActionPerformed

    private void modificarProveedoresBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonGuardarActionPerformed
        // TODO add your handling code here:
        id = modificarProveedoresEscribirID.getText().toString();
        empresa = modificarProveedoresEscribirEmpresa.getText().toString();
        telefono = modificarProveedoresEscribirTelefono.getText().toString();
        correo = modificarProveedoresEscribirCorreo.getText().toString();
        calle = modificarProveedoresEscribirCalle.getText().toString();
        numero = modificarProveedoresEscribirNumero.getText().toString();
        colonia = modificarProveedoresEscribirColonia.getText().toString();

        if (id.length() > 0) {
            if (empresa.length() > 0) {
                if (telefono.length() == 10) {
                    if (correo.length() > 0) {
                        if (calle.length() > 0) {
                            if (numero.length() > 0) {
                                if (colonia.length() > 0) {
                
                    try {
                    bd = new Conexion();
                    s = null;
                    s = Conexion.conectar().createStatement();

                    queryotro = "select * from proveedores where ID_proveedor='" + id + "';";
                    if (!bd.resultado(queryotro).next()) {

                        JOptionPane.showMessageDialog(null, "Este proveedor no existe");
                        modificarProveedoresEscribirID.setText(null);
                        modificarProveedoresEscribirID.requestFocus();
                        bd.cerrar();
                    } else {
                        actualizar = "UPDATE proveedores SET EMPRESA='" + empresa + "', TELEFONO='" + telefono + "', CORREO='"
                                + correo + "', CALLE='" + calle + "',  NUMERO='" + numero + "', COLONIA='" + colonia + "' WHERE ID_PROVEEDOR='" + id + "';";
                        s.execute(actualizar);

                        JOptionPane.showMessageDialog(null, "Se ah modificado correctamente");
                        modificarProveedoresEscribirID.setText(null);
                        modificarProveedoresEscribirEmpresa.setText(null);
                        modificarProveedoresEscribirTelefono.setText(null);
                        modificarProveedoresEscribirCorreo.setText(null);
                        modificarProveedoresEscribirCalle.setText(null);
                        modificarProveedoresEscribirNumero.setText(null);
                        modificarProveedoresEscribirColonia.setText(null);

                        modificarProveedoresEscribirID.enable(true);
                        modificarProveedoresEscribirEmpresa.enable(false);
                        modificarProveedoresEscribirTelefono.enable(false);
                        modificarProveedoresEscribirCorreo.enable(false);
                        modificarProveedoresEscribirCalle.enable(false);
                        modificarProveedoresEscribirNumero.enable(false);
                        modificarProveedoresEscribirColonia.enable(false);

                        modificarProveedoresEscribirID.requestFocus();
                        modificarProveedoresBotonGuardar.setEnabled(false);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
                }
            } else {
                                    JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                                    modificarProveedoresEscribirColonia.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                                modificarProveedoresEscribirNumero.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                            modificarProveedoresEscribirCalle.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                        modificarProveedoresEscribirCorreo.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                    modificarProveedoresEscribirTelefono.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                modificarProveedoresEscribirEmpresa.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor realiza una busqueda");
            modificarProveedoresEscribirID.requestFocus();
        }
    }//GEN-LAST:event_modificarProveedoresBotonGuardarActionPerformed

    private void modificarProveedoresBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonLimpiarActionPerformed
        // TODO add your handling code here:
        modificarProveedoresEscribirID.setText(null);
        modificarProveedoresEscribirEmpresa.setText(null);
        modificarProveedoresEscribirTelefono.setText(null);
        modificarProveedoresEscribirCorreo.setText(null);
        modificarProveedoresEscribirCalle.setText(null);
        modificarProveedoresEscribirNumero.setText(null);
        modificarProveedoresEscribirColonia.setText(null);

        modificarProveedoresEscribirID.enable(true);
        modificarProveedoresEscribirEmpresa.enable(false);
        modificarProveedoresEscribirTelefono.enable(false);
        modificarProveedoresEscribirCorreo.enable(false);
        modificarProveedoresEscribirCalle.enable(false);
        modificarProveedoresEscribirNumero.enable(false);
        modificarProveedoresEscribirColonia.enable(false);

        modificarProveedoresEscribirID.requestFocus();
        modificarProveedoresBotonGuardar.setEnabled(false);
    }//GEN-LAST:event_modificarProveedoresBotonLimpiarActionPerformed

    private void modificarProveedoresBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonBuscarActionPerformed
        // TODO add your handling code here:
        id = modificarProveedoresEscribirID.getText().toString();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa un ID");
            modificarProveedoresEscribirID.requestFocus();
        } else {

            try {
                bd = new Conexion();
                s = null;
                s = Conexion.conectar().createStatement();
                queryotro = "select * from proveedores where ID_proveedor='" + id + "';";
                res = bd.resultado(queryotro);

                if (res.next()) {

                    modificarProveedoresEscribirID.enable(false);
                    modificarProveedoresEscribirEmpresa.enable(true);
                    modificarProveedoresEscribirTelefono.enable(true);
                    modificarProveedoresEscribirCorreo.enable(true);
                    modificarProveedoresEscribirCalle.enable(true);
                    modificarProveedoresEscribirNumero.enable(true);
                    modificarProveedoresEscribirColonia.enable(true);

                    modificarProveedoresEscribirEmpresa.setText(res.getString("empresa"));
                    modificarProveedoresEscribirTelefono.setText(res.getString("telefono"));
                    modificarProveedoresEscribirCorreo.setText(res.getString("correo"));
                    modificarProveedoresEscribirCalle.setText(res.getString("calle"));
                    modificarProveedoresEscribirNumero.setText(res.getString("numero"));
                    modificarProveedoresEscribirColonia.setText(res.getString("colonia"));

                    modificarProveedoresEscribirEmpresa.requestFocus();
                    modificarProveedoresBotonGuardar.setEnabled(true);
                    bd.cerrar();
                } else {

                    JOptionPane.showMessageDialog(null, "el proveedor no existe");
                    modificarProveedoresEscribirID.setText(null);
                    modificarProveedoresEscribirID.requestFocus();

                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
            }
        }
    }//GEN-LAST:event_modificarProveedoresBotonBuscarActionPerformed

    private void modificarProveedoresEscribirTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedoresEscribirTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarProveedoresEscribirTelefonoActionPerformed

    private void modificarProveedoresBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonSalirActionPerformed
        // TODO add your handling code here:
        menuProveedores nuevo = new menuProveedores();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_modificarProveedoresBotonSalirActionPerformed

    private void resaltarModificarProveedoresID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProveedoresID
        // TODO add your handling code here:
        modificarProveedoresID.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresEscribirID.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProveedoresID

    private void restaurarModificarProveedoresID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProveedoresID
        // TODO add your handling code here:
        modificarProveedoresID.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresEscribirID.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_restaurarModificarProveedoresID

    private void resaltarModificarProveedoresEmpresa(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProveedoresEmpresa
        // TODO add your handling code here:
        modificarProveedoresEmpresa.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresEscribirEmpresa.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProveedoresEmpresa

    private void restaurarModificarProveedoresEmpresa(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProveedoresEmpresa
        // TODO add your handling code here:
        modificarProveedoresEmpresa.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresEscribirEmpresa.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProveedoresEmpresa

    private void resaltarModificarProveedoresTelefono(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProveedoresTelefono
        // TODO add your handling code here:
        modificarProveedoresTelefono.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresEscribirTelefono.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProveedoresTelefono

    private void restaurarModificarProveedoresTelefono(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProveedoresTelefono
        // TODO add your handling code here:
        modificarProveedoresTelefono.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresEscribirTelefono.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProveedoresTelefono

    private void resaltarModificarProveedoresCorreo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProveedoresCorreo
        // TODO add your handling code here:
        modificarProveedoresCorreo.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresEscribirCorreo.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProveedoresCorreo

    private void restaurarModificarProveedoresCorreo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProveedoresCorreo
        // TODO add your handling code here:
        modificarProveedoresCorreo.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresEscribirCorreo.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProveedoresCorreo

    private void resaltarModificarProveedoresCalle(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProveedoresCalle
        // TODO add your handling code here:
        modificarProveedoresCalle.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresEscribirCalle.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProveedoresCalle

    private void restaurarModificarProveedoresCalle(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProveedoresCalle
        // TODO add your handling code here:
        modificarProveedoresCalle.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresEscribirCalle.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProveedoresCalle

    private void resaltarModificarProveedoresNumero(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProveedoresNumero
        // TODO add your handling code here:
        modificarProveedoresNumero.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresEscribirNumero.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProveedoresNumero

    private void restaurarModificarProveedoresNumero(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProveedoresNumero
        // TODO add your handling code here:
        modificarProveedoresNumero.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresEscribirNumero.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProveedoresNumero

    private void resaltarModificarProveedoresColonia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarModificarProveedoresColonia
        // TODO add your handling code here:
        modificarProveedoresColonia.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresEscribirColonia.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarModificarProveedoresColonia

    private void restaurarModificarProveedoresColonia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarModificarProveedoresColonia
        // TODO add your handling code here:
        modificarProveedoresColonia.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresEscribirColonia.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarModificarProveedoresColonia

    private void verificarModificarProveedoresID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProveedoresID
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (modificarProveedoresEscribirID.getText().length() >= 20) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProveedoresID

    private void verificarModificarProveedoresEmpresa(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProveedoresEmpresa
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != '.') && (caracter != '-') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (modificarProveedoresEscribirEmpresa.getText().length() >= 30) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProveedoresEmpresa

    private void verificarModificarProveedoresTelefono(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProveedoresTelefono
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (modificarProveedoresEscribirTelefono.getText().length() >= 10) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProveedoresTelefono

    private void verificarModificarProveedoresCorreo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProveedoresCorreo
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C') && (caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != '-') && (caracter != '_') && (caracter != '.') && (caracter != '@') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (modificarProveedoresEscribirCorreo.getText().length() >= 70) {
            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProveedoresCorreo

    private void verificarModificarProveedoresCalle(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProveedoresCalle
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (modificarProveedoresEscribirCalle.getText().length() >= 30) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProveedoresCalle

    private void verificarModificarProveedoresNumero(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProveedoresNumero
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C') && (caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != 'ñ') && (caracter != 'Ñ')) {

            evt.consume();
        } else if (modificarProveedoresEscribirNumero.getText().length() >= 10) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProveedoresNumero

    private void verificarModificarProveedoresColonia(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarModificarProveedoresColonia
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();

        } else if (modificarProveedoresEscribirColonia.getText().length() >= 15) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarModificarProveedoresColonia

    private void modificarProveedoresBotonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonBuscarMouseEntered
        // TODO add your handling code here:
        modificarProveedoresBotonBuscar.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresBotonBuscar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_modificarProveedoresBotonBuscarMouseEntered

    private void modificarProveedoresBotonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonBuscarMouseExited
        // TODO add your handling code here:
        modificarProveedoresBotonBuscar.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresBotonBuscar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_modificarProveedoresBotonBuscarMouseExited

    private void modificarProveedoresBotonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonGuardarMouseEntered
        // TODO add your handling code here:
        modificarProveedoresBotonGuardar.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresBotonGuardar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_modificarProveedoresBotonGuardarMouseEntered

    private void modificarProveedoresBotonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonGuardarMouseExited
        // TODO add your handling code here:
        modificarProveedoresBotonGuardar.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresBotonGuardar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_modificarProveedoresBotonGuardarMouseExited

    private void modificarProveedoresBotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonLimpiarMouseEntered
        // TODO add your handling code here:
        modificarProveedoresBotonLimpiar.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresBotonLimpiar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_modificarProveedoresBotonLimpiarMouseEntered

    private void modificarProveedoresBotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonLimpiarMouseExited
        // TODO add your handling code here:
        modificarProveedoresBotonLimpiar.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresBotonLimpiar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_modificarProveedoresBotonLimpiarMouseExited

    private void modificarProveedoresBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonSalirMouseEntered
        // TODO add your handling code here:
        modificarProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        modificarProveedoresBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_modificarProveedoresBotonSalirMouseEntered

    private void modificarProveedoresBotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarProveedoresBotonSalirMouseExited
        // TODO add your handling code here:
        modificarProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        modificarProveedoresBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_modificarProveedoresBotonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton modificarProveedoresBotonBuscar;
    private javax.swing.JButton modificarProveedoresBotonGuardar;
    private javax.swing.JButton modificarProveedoresBotonLimpiar;
    private javax.swing.JButton modificarProveedoresBotonSalir;
    private javax.swing.JLabel modificarProveedoresCalle;
    private javax.swing.JLabel modificarProveedoresColonia;
    private javax.swing.JLabel modificarProveedoresCorreo;
    private javax.swing.JPanel modificarProveedoresCuerpo;
    private javax.swing.JLabel modificarProveedoresEmpresa;
    private javax.swing.JPanel modificarProveedoresEncabezado;
    private javax.swing.JTextField modificarProveedoresEscribirCalle;
    private javax.swing.JTextField modificarProveedoresEscribirColonia;
    private javax.swing.JTextField modificarProveedoresEscribirCorreo;
    private javax.swing.JTextField modificarProveedoresEscribirEmpresa;
    private javax.swing.JTextField modificarProveedoresEscribirID;
    private javax.swing.JTextField modificarProveedoresEscribirNumero;
    private javax.swing.JTextField modificarProveedoresEscribirTelefono;
    private javax.swing.JLabel modificarProveedoresID;
    private javax.swing.JLabel modificarProveedoresNumero;
    private javax.swing.JPanel modificarProveedoresPie;
    private javax.swing.JLabel modificarProveedoresTelefono;
    private javax.swing.JLabel modificarProveedoresTitulo;
    // End of variables declaration//GEN-END:variables
}
