/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class registrarVentas extends javax.swing.JFrame {

    String id, dia, mes, año, producto, cliente, total, queryotro, insertar;
    double precio, totalProducto;
    int cantidad;
    Conexion bd;
    ResultSet res;
    Statement s;

    /**
     * Creates new form registrarVentas
     */
    public registrarVentas() {
        initComponents();
        registrarVentasEscribirCliente.removeAllItems();
    }
    int bandera = 0;
    ArrayList<String> listaClientes = new ArrayList<String>();
    int bandera2 = 0;
    ArrayList<String> listaClientes2 = new ArrayList<String>();
    DefaultComboBoxModel modelo = new DefaultComboBoxModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarVentasEncabezado = new javax.swing.JPanel();
        registrarVentasTitulo = new javax.swing.JLabel();
        registrarVentasCuerpo = new javax.swing.JPanel();
        registrarVentasD = new javax.swing.JLabel();
        registrarVentasFecha = new javax.swing.JLabel();
        registrarVentasCostoTotal = new javax.swing.JLabel();
        registrarVentasEscribirCostoTotal = new javax.swing.JTextField();
        registrarVentasEscribirID = new javax.swing.JTextField();
        registrarVentasEscribirDia = new javax.swing.JComboBox<>();
        registrarVentasEscribirMes = new javax.swing.JComboBox<>();
        registrarVentasEscribirAño = new javax.swing.JComboBox<>();
        registrarComprasCliente = new javax.swing.JLabel();
        registrarVentasEscribirCliente = new javax.swing.JComboBox<>();
        registrarVentasPie = new javax.swing.JPanel();
        registrarVentasBotonAgregar = new javax.swing.JButton();
        registrarVentasBotonSalir = new javax.swing.JButton();
        registrarVentasBotonLimpiar = new javax.swing.JButton();
        registrarVentasBotonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                registrarVentasCargarClientes(evt);
            }
        });

        registrarVentasEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        registrarVentasEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        registrarVentasTitulo.setBackground(new java.awt.Color(0, 0, 0));
        registrarVentasTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        registrarVentasTitulo.setForeground(new java.awt.Color(255, 255, 255));
        registrarVentasTitulo.setText("Registrar ventas");
        registrarVentasTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout registrarVentasEncabezadoLayout = new javax.swing.GroupLayout(registrarVentasEncabezado);
        registrarVentasEncabezado.setLayout(registrarVentasEncabezadoLayout);
        registrarVentasEncabezadoLayout.setHorizontalGroup(
            registrarVentasEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarVentasEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarVentasTitulo)
                .addGap(78, 78, 78))
        );
        registrarVentasEncabezadoLayout.setVerticalGroup(
            registrarVentasEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarVentasEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarVentasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        registrarVentasCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        registrarVentasCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasCuerpo.setForeground(new java.awt.Color(255, 255, 255));

        registrarVentasD.setBackground(new java.awt.Color(0, 0, 0));
        registrarVentasD.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasD.setForeground(new java.awt.Color(255, 255, 255));
        registrarVentasD.setText("ID de la venta");

        registrarVentasFecha.setBackground(new java.awt.Color(0, 0, 0));
        registrarVentasFecha.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasFecha.setForeground(new java.awt.Color(255, 255, 255));
        registrarVentasFecha.setText("Fecha");

        registrarVentasCostoTotal.setBackground(new java.awt.Color(0, 0, 0));
        registrarVentasCostoTotal.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasCostoTotal.setForeground(new java.awt.Color(255, 255, 255));
        registrarVentasCostoTotal.setText("Total a recibir");

        registrarVentasEscribirCostoTotal.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasEscribirCostoTotal.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasEscribirCostoTotal.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasEscribirCostoTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasEscribirCostoTotal.setEnabled(false);

        registrarVentasEscribirID.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasEscribirID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasEscribirID.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasEscribirID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasEscribirID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarVentasID(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarVentasID(evt);
            }
        });
        registrarVentasEscribirID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarIRegistrarVentasID(evt);
            }
        });

        registrarVentasEscribirDia.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasEscribirDia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasEscribirDia.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasEscribirDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        registrarVentasEscribirDia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasEscribirDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarVentasFechaDia(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarVentasFechaDia(evt);
            }
        });

        registrarVentasEscribirMes.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasEscribirMes.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasEscribirMes.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasEscribirMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        registrarVentasEscribirMes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasEscribirMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarVentasFechaMes(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarVentasFechaMes(evt);
            }
        });

        registrarVentasEscribirAño.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasEscribirAño.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasEscribirAño.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasEscribirAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        registrarVentasEscribirAño.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasEscribirAño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarVentasFechaAño(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarVentasFechaAño(evt);
            }
        });

        registrarComprasCliente.setBackground(new java.awt.Color(0, 0, 0));
        registrarComprasCliente.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarComprasCliente.setForeground(new java.awt.Color(255, 255, 255));
        registrarComprasCliente.setText("Cliente");
        registrarComprasCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarVentasEscribirCliente.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasEscribirCliente.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasEscribirCliente.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasEscribirCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasEscribirCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                registrarVentasEscribirClienteItemStateChanged(evt);
            }
        });
        registrarVentasEscribirCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registrarVentasEscribirClienteresaltarRegistrarComprasProveedor(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registrarVentasEscribirClienterestaurarRegistrarComprasProveedor(evt);
            }
        });

        javax.swing.GroupLayout registrarVentasCuerpoLayout = new javax.swing.GroupLayout(registrarVentasCuerpo);
        registrarVentasCuerpo.setLayout(registrarVentasCuerpoLayout);
        registrarVentasCuerpoLayout.setHorizontalGroup(
            registrarVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarVentasCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarVentasCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarVentasFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarVentasEscribirDia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarVentasEscribirMes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarVentasEscribirAño, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrarVentasCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarVentasD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarVentasEscribirID))
                    .addGroup(registrarVentasCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarVentasCostoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarVentasEscribirCostoTotal))
                    .addGroup(registrarVentasCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarComprasCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registrarVentasEscribirCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        registrarVentasCuerpoLayout.setVerticalGroup(
            registrarVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarVentasCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarVentasD)
                    .addComponent(registrarVentasEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registrarVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarVentasEscribirDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarVentasEscribirMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarVentasEscribirAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarVentasFecha))
                .addGap(18, 18, 18)
                .addGroup(registrarVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarComprasCliente)
                    .addComponent(registrarVentasEscribirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registrarVentasCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarVentasCostoTotal)
                    .addComponent(registrarVentasEscribirCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registrarVentasPie.setBackground(new java.awt.Color(0, 0, 0));
        registrarVentasPie.setForeground(new java.awt.Color(255, 255, 255));

        registrarVentasBotonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasBotonAgregar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasBotonAgregar.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasBotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.jpg"))); // NOI18N
        registrarVentasBotonAgregar.setText("Agregar venta");
        registrarVentasBotonAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasBotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarVentasBotonAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarVentasBotonAgregarMouseExited(evt);
            }
        });
        registrarVentasBotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentasBotonAgregarActionPerformed(evt);
            }
        });

        registrarVentasBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasBotonSalir.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        registrarVentasBotonSalir.setText("Salir");
        registrarVentasBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarVentasBotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarVentasBotonSalirMouseExited(evt);
            }
        });
        registrarVentasBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentasBotonSalirActionPerformed(evt);
            }
        });

        registrarVentasBotonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasBotonLimpiar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasBotonLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasBotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        registrarVentasBotonLimpiar.setText("Limpiar");
        registrarVentasBotonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasBotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarVentasBotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarVentasBotonLimpiarMouseExited(evt);
            }
        });
        registrarVentasBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentasBotonLimpiarActionPerformed(evt);
            }
        });

        registrarVentasBotonModificar.setBackground(new java.awt.Color(255, 255, 255));
        registrarVentasBotonModificar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarVentasBotonModificar.setForeground(new java.awt.Color(0, 0, 0));
        registrarVentasBotonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar.jpg"))); // NOI18N
        registrarVentasBotonModificar.setText("Modificar");
        registrarVentasBotonModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarVentasBotonModificar.setEnabled(false);
        registrarVentasBotonModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarVentasBotonModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarVentasBotonModificarMouseExited(evt);
            }
        });
        registrarVentasBotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarVentasBotonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarVentasPieLayout = new javax.swing.GroupLayout(registrarVentasPie);
        registrarVentasPie.setLayout(registrarVentasPieLayout);
        registrarVentasPieLayout.setHorizontalGroup(
            registrarVentasPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarVentasPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarVentasBotonAgregar)
                .addGap(28, 28, 28)
                .addGroup(registrarVentasPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarVentasBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registrarVentasPieLayout.createSequentialGroup()
                        .addComponent(registrarVentasBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarVentasBotonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        registrarVentasPieLayout.setVerticalGroup(
            registrarVentasPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarVentasPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarVentasPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarVentasBotonAgregar)
                    .addComponent(registrarVentasBotonLimpiar)
                    .addComponent(registrarVentasBotonModificar))
                .addGap(18, 18, 18)
                .addComponent(registrarVentasBotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarVentasEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarVentasPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarVentasCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarVentasEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarVentasCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarVentasPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resaltarRegistrarVentasID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarVentasID
        // TODO add your handling code here:
        registrarVentasD.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasEscribirID.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarVentasID

    private void restaurarRegistrarVentasID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarVentasID
        // TODO add your handling code here:
        registrarVentasD.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasEscribirID.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarVentasID

    private void verificarIRegistrarVentasID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarIRegistrarVentasID
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (registrarVentasEscribirID.getText().length() >= 20) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarIRegistrarVentasID

    private void resaltarRegistrarVentasFechaDia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarVentasFechaDia
        // TODO add your handling code here:
        registrarVentasFecha.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasEscribirDia.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarVentasFechaDia

    private void restaurarRegistrarVentasFechaDia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarVentasFechaDia
        // TODO add your handling code here:
        registrarVentasFecha.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasEscribirDia.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarVentasFechaDia

    private void resaltarRegistrarVentasFechaMes(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarVentasFechaMes
        // TODO add your handling code here:
        registrarVentasFecha.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasEscribirMes.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarVentasFechaMes

    private void restaurarRegistrarVentasFechaMes(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarVentasFechaMes
        // TODO add your handling code here:
        registrarVentasFecha.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasEscribirMes.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarVentasFechaMes

    private void resaltarRegistrarVentasFechaAño(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarVentasFechaAño
        // TODO add your handling code here:
        registrarVentasFecha.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasEscribirAño.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarVentasFechaAño

    private void restaurarRegistrarVentasFechaAño(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarVentasFechaAño
        // TODO add your handling code here:
        registrarVentasFecha.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasEscribirAño.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarVentasFechaAño

    private void registrarVentasBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentasBotonSalirActionPerformed
        // TODO add your handling code here:
        menuVentas nuevo = new menuVentas();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_registrarVentasBotonSalirActionPerformed

    private void registrarVentasBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentasBotonLimpiarActionPerformed
        // TODO add your handling code here:
        registrarVentasEscribirID.setText(null);
        registrarVentasEscribirDia.setSelectedIndex(0);
        registrarVentasEscribirMes.setSelectedIndex(0);
        registrarVentasEscribirAño.setSelectedIndex(0);
        registrarVentasEscribirCliente.setSelectedIndex(0);
        
        try {
            bd = new Conexion();
            s = null;
            s = Conexion.conectar().createStatement();
            res = s.executeQuery("select * from clientes");
            while (res.next()) {

                listaClientes2.add(res.getString("nombre_completo"));
                //listaProveedores.add(res.getString("Empresa"));
                //res.next();
                //modelo.addItem(listaproductos);
            }

            if (bandera2 == 0) {
                registrarVentasEscribirCliente.removeAllItems();
                registrarVentasEscribirCliente.addItem("Cliente");//posicion 0 de la lista del combo
                for (int i = 0; i <= listaClientes2.size(); i++) {
                    registrarVentasEscribirCliente.addItem(listaClientes2.get(i));
                    bandera2 = 1;
                }
            }

        } catch (Exception e) {

        }
        
        registrarVentasEscribirCostoTotal.setText(null);

        registrarVentasEscribirID.enable(true);
        registrarVentasEscribirDia.enable(true);
        registrarVentasEscribirMes.enable(true);
        registrarVentasEscribirAño.enable(true);
        registrarVentasEscribirCliente.enable(true);
        registrarVentasBotonAgregar.setEnabled(true);
        registrarVentasBotonModificar.setEnabled(false);

        registrarVentasEscribirID.requestFocus();
    }//GEN-LAST:event_registrarVentasBotonLimpiarActionPerformed

    private void registrarVentasBotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentasBotonAgregarActionPerformed
        // TODO add your handling code here:
        id = registrarVentasEscribirID.getText().toString();
        dia = registrarVentasEscribirDia.getSelectedItem().toString();
        mes = registrarVentasEscribirMes.getSelectedItem().toString();
        año = registrarVentasEscribirAño.getSelectedItem().toString();
        cliente = registrarVentasEscribirCliente.getSelectedItem().toString();

        if (id.length() > 0) {
            if (dia.length() == 2) {
                if (mes.length() == 2) {
                    if (año.length() == 4) {
                        if (registrarVentasEscribirCliente.getSelectedIndex() > 0) {

                        try {
                            bd = new Conexion();
                            s = null;
                            s = Conexion.conectar().createStatement();
                            queryotro = "select * from ventas where ID_venta='" + id + "';";

                            if (bd.resultado(queryotro).next()) {
                                JOptionPane.showMessageDialog(null, "Ya esta registrado una compra con el mismo ID");
                                registrarVentasEscribirID.setText("");
                                registrarVentasEscribirID.requestFocus();
                                bd.cerrar();
                            } else {
                                ResultSet res2 = s.executeQuery("select id_cliente from clientes where Nombre_completo='" + cliente + "';");
                                if (res2.next()) {
                                    cliente = res2.getString("id_cliente");
                                    insertar = "insert into ventas values ('" + id + "', '" + dia + "', '" + mes + "', '" + año + "', '" + cliente + "' , default)";
                                    s.execute(insertar);

                                    //detallesCompras.detallesComprasEscribirID.setText(registrarComprasEscribirID.getText());
                                    detallesVentas nuevo = new detallesVentas();
                                    this.setVisible(false);
                                    nuevo.setVisible(true);
                                    detallesVentas.detallesVentasEscribirID.setText(registrarVentasEscribirID.getText());
                                }
                            }
                            }catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
                        }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor rellena los campos correctamente");
                            registrarVentasEscribirCliente.requestFocus();
                        }
                        }else {
                            JOptionPane.showMessageDialog(null, "Por favor rellena los campos correctamente");
                            registrarVentasEscribirAño.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor rellena los campos correctamente");
                        registrarVentasEscribirMes.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor rellena los campos correctamente");
                    registrarVentasEscribirDia.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor rellena los campos correctamente");
                registrarVentasEscribirID.requestFocus();
            }


    }//GEN-LAST:event_registrarVentasBotonAgregarActionPerformed

    private void registrarVentasBotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarVentasBotonModificarActionPerformed
        // TODO add your handling code here:
        detallesVentas nuevo = new detallesVentas();
        this.setVisible(false);
        nuevo.setVisible(true);
        detallesVentas.detallesVentasEscribirID.setText(registrarVentasEscribirID.getText());
    }//GEN-LAST:event_registrarVentasBotonModificarActionPerformed

    private void registrarVentasEscribirClienteresaltarRegistrarComprasProveedor(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registrarVentasEscribirClienteresaltarRegistrarComprasProveedor
        // TODO add your handling code here:
        registrarComprasCliente.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasEscribirCliente.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarVentasEscribirClienteresaltarRegistrarComprasProveedor

    private void registrarVentasEscribirClienterestaurarRegistrarComprasProveedor(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registrarVentasEscribirClienterestaurarRegistrarComprasProveedor
        // TODO add your handling code here:
        registrarComprasCliente.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasEscribirCliente.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarVentasEscribirClienterestaurarRegistrarComprasProveedor

    private void registrarVentasCargarClientes(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_registrarVentasCargarClientes
        // TODO add your handling code here:
        try {
            bd = new Conexion();
            s = null;
            s = Conexion.conectar().createStatement();
            res = s.executeQuery("select * from Clientes");
            while (res.next()) {

                listaClientes.add(res.getString("Nombre_completo"));
            }

            if (bandera == 0) {
                registrarVentasEscribirCliente.addItem("Cliente");//posicion 0 de la lista del combo
                for (int i = 0; i <= listaClientes.size(); i++) {
                    registrarVentasEscribirCliente.addItem(listaClientes.get(i));
                    bandera = 1;
                }
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_registrarVentasCargarClientes

    private void registrarVentasBotonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonAgregarMouseEntered
        // TODO add your handling code here:
        registrarVentasBotonAgregar.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasBotonAgregar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarVentasBotonAgregarMouseEntered

    private void registrarVentasBotonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonAgregarMouseExited
        // TODO add your handling code here:
        registrarVentasBotonAgregar.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasBotonAgregar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarVentasBotonAgregarMouseExited

    private void registrarVentasBotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonLimpiarMouseEntered
        // TODO add your handling code here:
        registrarVentasBotonLimpiar.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasBotonLimpiar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarVentasBotonLimpiarMouseEntered

    private void registrarVentasBotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonLimpiarMouseExited
        // TODO add your handling code here:
        registrarVentasBotonLimpiar.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasBotonLimpiar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarVentasBotonLimpiarMouseExited

    private void registrarVentasBotonModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonModificarMouseEntered
        // TODO add your handling code here:
        registrarVentasBotonModificar.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasBotonModificar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarVentasBotonModificarMouseEntered

    private void registrarVentasBotonModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonModificarMouseExited
        // TODO add your handling code here:
        registrarVentasBotonModificar.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasBotonModificar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarVentasBotonModificarMouseExited

    private void registrarVentasBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonSalirMouseEntered
        // TODO add your handling code here:
        registrarVentasBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarVentasBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarVentasBotonSalirMouseEntered

    private void registrarVentasBotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarVentasBotonSalirMouseExited
        // TODO add your handling code here:
        registrarVentasBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarVentasBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarVentasBotonSalirMouseExited

    private void registrarVentasEscribirClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_registrarVentasEscribirClienteItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_registrarVentasEscribirClienteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel registrarComprasCliente;
    public static javax.swing.JButton registrarVentasBotonAgregar;
    private javax.swing.JButton registrarVentasBotonLimpiar;
    public static javax.swing.JButton registrarVentasBotonModificar;
    private javax.swing.JButton registrarVentasBotonSalir;
    private javax.swing.JLabel registrarVentasCostoTotal;
    private javax.swing.JPanel registrarVentasCuerpo;
    private javax.swing.JLabel registrarVentasD;
    private javax.swing.JPanel registrarVentasEncabezado;
    public static javax.swing.JComboBox<String> registrarVentasEscribirAño;
    public static javax.swing.JComboBox<String> registrarVentasEscribirCliente;
    public static javax.swing.JTextField registrarVentasEscribirCostoTotal;
    public static javax.swing.JComboBox<String> registrarVentasEscribirDia;
    public static javax.swing.JTextField registrarVentasEscribirID;
    public static javax.swing.JComboBox<String> registrarVentasEscribirMes;
    private javax.swing.JLabel registrarVentasFecha;
    private javax.swing.JPanel registrarVentasPie;
    private javax.swing.JLabel registrarVentasTitulo;
    // End of variables declaration//GEN-END:variables
}
