/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;
import Clases.Conexion;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;

/**
 *
 * @author David Franco
 */
public class registrarProveedores extends javax.swing.JFrame {

    String id, empresa, telefono, correo, calle, numero, colonia, queryotro, insertar;
    Conexion bd;
    Statement s;

    /**
     * Creates new form registrarProveedores
     */
    public registrarProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarProveedoresEncabezado = new javax.swing.JPanel();
        registrarProveedoresTitulo = new javax.swing.JLabel();
        registrarProveedoresCuerpo = new javax.swing.JPanel();
        registrarProveedoresID = new javax.swing.JLabel();
        registrarProveedoresEmpresa = new javax.swing.JLabel();
        registrarProveedoresTelefono = new javax.swing.JLabel();
        registrarProveedoresCorreo = new javax.swing.JLabel();
        registrarProveedoresCalle = new javax.swing.JLabel();
        registrarProveedoresNumero = new javax.swing.JLabel();
        registrarProveedoresColonia = new javax.swing.JLabel();
        registrarProveedoresEscribirEmpresa = new javax.swing.JTextField();
        registrarProveedoresEscribirID = new javax.swing.JTextField();
        registrarProveedoresEscribirCorreo = new javax.swing.JTextField();
        registrarProveedoresEscribirTelefono = new javax.swing.JTextField();
        registrarProveedoresEscribirCalle = new javax.swing.JTextField();
        registrarProveedoresEscribirNumero = new javax.swing.JTextField();
        registrarProveedoresEscribirColonia = new javax.swing.JTextField();
        registrarProveedoresPie = new javax.swing.JPanel();
        registrarProveedoresBotonGuardar = new javax.swing.JButton();
        registrarProveedoresBotonSalir = new javax.swing.JButton();
        registrarProveedoresBotonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        registrarProveedoresEncabezado.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresEncabezado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEncabezado.setForeground(new java.awt.Color(255, 255, 255));

        registrarProveedoresTitulo.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresTitulo.setFont(new java.awt.Font("Javanese Text", 1, 26)); // NOI18N
        registrarProveedoresTitulo.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresTitulo.setText("Registrar proveedores");
        registrarProveedoresTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout registrarProveedoresEncabezadoLayout = new javax.swing.GroupLayout(registrarProveedoresEncabezado);
        registrarProveedoresEncabezado.setLayout(registrarProveedoresEncabezadoLayout);
        registrarProveedoresEncabezadoLayout.setHorizontalGroup(
            registrarProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProveedoresEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarProveedoresTitulo)
                .addGap(52, 52, 52))
        );
        registrarProveedoresEncabezadoLayout.setVerticalGroup(
            registrarProveedoresEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProveedoresEncabezadoLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(registrarProveedoresTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        registrarProveedoresCuerpo.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresCuerpo.setForeground(new java.awt.Color(255, 255, 255));

        registrarProveedoresID.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresID.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresID.setText("ID del proveedor");
        registrarProveedoresID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresEmpresa.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresEmpresa.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresEmpresa.setText("Nombre de la empresa");
        registrarProveedoresEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresTelefono.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresTelefono.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresTelefono.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresTelefono.setText("Numero de telefono");
        registrarProveedoresTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresCorreo.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresCorreo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresCorreo.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresCorreo.setText("Correo electronico");
        registrarProveedoresCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresCalle.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresCalle.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresCalle.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresCalle.setText("Calle donde se ubica");
        registrarProveedoresCalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresNumero.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresNumero.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresNumero.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresNumero.setText("Numero de domicilio");
        registrarProveedoresNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresColonia.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresColonia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresColonia.setForeground(new java.awt.Color(255, 255, 255));
        registrarProveedoresColonia.setText("Colonia");
        registrarProveedoresColonia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresEscribirEmpresa.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEscribirEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEscribirEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarProveedoresEmpresa(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarProveedoresEmpresa(evt);
            }
        });
        registrarProveedoresEscribirEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarRegistrarProveedoresEmpresa(evt);
            }
        });

        registrarProveedoresEscribirID.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEscribirID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEscribirID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarProveedoresID(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarProveedoresID(evt);
            }
        });
        registrarProveedoresEscribirID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarRegistrarProveedoresID(evt);
            }
        });

        registrarProveedoresEscribirCorreo.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEscribirCorreo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEscribirCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarProveedoresCorreo(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarProveedoresCorreo(evt);
            }
        });
        registrarProveedoresEscribirCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarRegistrarProveedoresCorreo(evt);
            }
        });

        registrarProveedoresEscribirTelefono.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEscribirTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEscribirTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarProveedoresTelefono(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarProveedoresTelefono(evt);
            }
        });
        registrarProveedoresEscribirTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProveedoresEscribirTelefonoActionPerformed(evt);
            }
        });
        registrarProveedoresEscribirTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarRegistrarProveedoresTelefono(evt);
            }
        });

        registrarProveedoresEscribirCalle.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEscribirCalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEscribirCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarProveedoresCalle(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarProveedoresCalle(evt);
            }
        });
        registrarProveedoresEscribirCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarRegistrarProveedoresCalle(evt);
            }
        });

        registrarProveedoresEscribirNumero.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEscribirNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEscribirNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarProveedoresNumero(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarProveedoresNumero(evt);
            }
        });
        registrarProveedoresEscribirNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificiarRegistrarProveedoresNumero(evt);
            }
        });

        registrarProveedoresEscribirColonia.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresEscribirColonia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresEscribirColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resaltarRegistrarProveedoresColonia(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restaurarRegistrarProveedoresColonia(evt);
            }
        });
        registrarProveedoresEscribirColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificarRegistrarProveedoresColonia(evt);
            }
        });

        javax.swing.GroupLayout registrarProveedoresCuerpoLayout = new javax.swing.GroupLayout(registrarProveedoresCuerpo);
        registrarProveedoresCuerpo.setLayout(registrarProveedoresCuerpoLayout);
        registrarProveedoresCuerpoLayout.setHorizontalGroup(
            registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarProveedoresCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarProveedoresColonia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarProveedoresEscribirColonia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProveedoresCuerpoLayout.createSequentialGroup()
                        .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarProveedoresCorreo)
                            .addComponent(registrarProveedoresCalle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarProveedoresEscribirCalle)
                            .addComponent(registrarProveedoresEscribirCorreo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProveedoresCuerpoLayout.createSequentialGroup()
                        .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarProveedoresTelefono)
                            .addComponent(registrarProveedoresEmpresa))
                        .addGap(7, 7, 7)
                        .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarProveedoresEscribirTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(registrarProveedoresEscribirEmpresa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarProveedoresID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarProveedoresEscribirID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarProveedoresCuerpoLayout.createSequentialGroup()
                        .addComponent(registrarProveedoresNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarProveedoresEscribirNumero)))
                .addContainerGap())
        );
        registrarProveedoresCuerpoLayout.setVerticalGroup(
            registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarProveedoresCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresID)
                    .addComponent(registrarProveedoresEscribirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresEmpresa)
                    .addComponent(registrarProveedoresEscribirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresTelefono)
                    .addComponent(registrarProveedoresEscribirTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresCorreo)
                    .addComponent(registrarProveedoresEscribirCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresCalle)
                    .addComponent(registrarProveedoresEscribirCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresNumero)
                    .addComponent(registrarProveedoresEscribirNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrarProveedoresCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresColonia)
                    .addComponent(registrarProveedoresEscribirColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registrarProveedoresPie.setBackground(new java.awt.Color(0, 0, 0));
        registrarProveedoresPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        registrarProveedoresBotonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        registrarProveedoresBotonGuardar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresBotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.jpg"))); // NOI18N
        registrarProveedoresBotonGuardar.setText("Guardar");
        registrarProveedoresBotonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarProveedoresBotonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarProveedoresBotonGuardarMouseExited(evt);
            }
        });
        registrarProveedoresBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProveedoresBotonGuardarActionPerformed(evt);
            }
        });

        registrarProveedoresBotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        registrarProveedoresBotonSalir.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresBotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        registrarProveedoresBotonSalir.setText("Salir");
        registrarProveedoresBotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresBotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarProveedoresBotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarProveedoresBotonSalirMouseExited(evt);
            }
        });
        registrarProveedoresBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProveedoresBotonSalirActionPerformed(evt);
            }
        });

        registrarProveedoresBotonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        registrarProveedoresBotonLimpiar.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        registrarProveedoresBotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar.jpg"))); // NOI18N
        registrarProveedoresBotonLimpiar.setText("Limpiar");
        registrarProveedoresBotonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarProveedoresBotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarProveedoresBotonLimpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarProveedoresBotonLimpiarMouseExited(evt);
            }
        });
        registrarProveedoresBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProveedoresBotonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarProveedoresPieLayout = new javax.swing.GroupLayout(registrarProveedoresPie);
        registrarProveedoresPie.setLayout(registrarProveedoresPieLayout);
        registrarProveedoresPieLayout.setHorizontalGroup(
            registrarProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarProveedoresPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarProveedoresBotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(registrarProveedoresBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(registrarProveedoresBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        registrarProveedoresPieLayout.setVerticalGroup(
            registrarProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarProveedoresPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrarProveedoresPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarProveedoresBotonGuardar)
                    .addComponent(registrarProveedoresBotonSalir)
                    .addComponent(registrarProveedoresBotonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarProveedoresCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarProveedoresEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarProveedoresPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrarProveedoresEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarProveedoresCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarProveedoresPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarProveedoresBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonGuardarActionPerformed
        // TODO add your handling code here:
        id = registrarProveedoresEscribirID.getText().toString();
        empresa = registrarProveedoresEscribirEmpresa.getText().toString();
        telefono = registrarProveedoresEscribirTelefono.getText().toString();
        correo = registrarProveedoresEscribirCorreo.getText().toString();
        calle = registrarProveedoresEscribirCalle.getText().toString();
        numero = registrarProveedoresEscribirNumero.getText().toString();
        colonia = registrarProveedoresEscribirColonia.getText().toString();

        if (id.length() > 0) {
            if (empresa.length() > 0) {
                if (telefono.length() == 10) {
                    if (correo.length() > 0) {
                        if (calle.length() > 0) {
                            if (numero.length() > 0) {
                                if (colonia.length() > 0) {

                                    try {
                                        bd = new Conexion();
                                        s = null;
                                        s = Conexion.conectar().createStatement();

                                        queryotro = "select * from proveedores where ID_proveedor='" + id + "';";
                                        if (bd.resultado(queryotro).next()) {

                                            JOptionPane.showMessageDialog(null, "Ya esta registrado un proveedor con el mismo ID");
                                            registrarProveedoresEscribirID.setText("");
                                            registrarProveedoresEscribirID.requestFocus();
                                            bd.cerrar();
                                        } else {

                                            insertar = "insert into proveedores values ('" + id + "', '" + empresa + "', '" + telefono + "', '" + correo + "', '" + calle + "', '" + numero + "', '" + colonia + "');";
                                            s.execute(insertar);

                                            JOptionPane.showMessageDialog(null, "Se ah insertado correctamente");
                                            registrarProveedoresEscribirID.setText(null);
                                            registrarProveedoresEscribirEmpresa.setText(null);
                                            registrarProveedoresEscribirTelefono.setText(null);
                                            registrarProveedoresEscribirCorreo.setText(null);
                                            registrarProveedoresEscribirCalle.setText(null);
                                            registrarProveedoresEscribirNumero.setText(null);
                                            registrarProveedoresEscribirColonia.setText(null);
                                            registrarProveedoresEscribirID.requestFocus();
                                        }
                                    } catch (SQLException e) {
                                        JOptionPane.showMessageDialog(null, "Se ah generado un error," + e);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                                    registrarProveedoresEscribirColonia.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                                registrarProveedoresEscribirNumero.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                            registrarProveedoresEscribirCalle.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                        registrarProveedoresEscribirCorreo.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                    registrarProveedoresEscribirTelefono.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
                registrarProveedoresEscribirEmpresa.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos correctamente");
            registrarProveedoresEscribirID.requestFocus();
        }

    }//GEN-LAST:event_registrarProveedoresBotonGuardarActionPerformed

    private void registrarProveedoresBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonLimpiarActionPerformed
        // TODO add your handling code here:
        registrarProveedoresEscribirID.setText(null);
        registrarProveedoresEscribirEmpresa.setText(null);
        registrarProveedoresEscribirTelefono.setText(null);
        registrarProveedoresEscribirCorreo.setText(null);
        registrarProveedoresEscribirCalle.setText(null);
        registrarProveedoresEscribirNumero.setText(null);
        registrarProveedoresEscribirColonia.setText(null);

        registrarProveedoresEscribirID.requestFocus();
    }//GEN-LAST:event_registrarProveedoresBotonLimpiarActionPerformed

    private void registrarProveedoresBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonSalirActionPerformed
        // TODO add your handling code here:
        menuProveedores nuevo = new menuProveedores();
        this.setVisible(false);
        nuevo.setVisible(true);
    }//GEN-LAST:event_registrarProveedoresBotonSalirActionPerformed

    private void resaltarRegistrarProveedoresID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarProveedoresID
        // TODO add your handling code here:
        registrarProveedoresID.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresEscribirID.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarProveedoresID

    private void restaurarRegistrarProveedoresID(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarProveedoresID
        // TODO add your handling code here:
        registrarProveedoresID.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresEscribirID.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_restaurarRegistrarProveedoresID

    private void resaltarRegistrarProveedoresEmpresa(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarProveedoresEmpresa
        // TODO add your handling code here:
        registrarProveedoresEmpresa.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresEscribirEmpresa.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarProveedoresEmpresa

    private void restaurarRegistrarProveedoresEmpresa(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarProveedoresEmpresa
        // TODO add your handling code here:
        registrarProveedoresEmpresa.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresEscribirEmpresa.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarProveedoresEmpresa

    private void resaltarRegistrarProveedoresTelefono(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarProveedoresTelefono
        // TODO add your handling code here:
        registrarProveedoresTelefono.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresEscribirTelefono.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarProveedoresTelefono

    private void restaurarRegistrarProveedoresTelefono(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarProveedoresTelefono
        // TODO add your handling code here:
        registrarProveedoresTelefono.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresEscribirTelefono.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarProveedoresTelefono

    private void resaltarRegistrarProveedoresCorreo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarProveedoresCorreo
        // TODO add your handling code here:
        registrarProveedoresCorreo.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresEscribirCorreo.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarProveedoresCorreo

    private void restaurarRegistrarProveedoresCorreo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarProveedoresCorreo
        // TODO add your handling code here:
        registrarProveedoresCorreo.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresEscribirCorreo.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarProveedoresCorreo

    private void resaltarRegistrarProveedoresCalle(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarProveedoresCalle
        // TODO add your handling code here:
        registrarProveedoresCalle.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresEscribirCalle.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarProveedoresCalle

    private void restaurarRegistrarProveedoresCalle(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarProveedoresCalle
        // TODO add your handling code here:
        registrarProveedoresCalle.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresEscribirCalle.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarProveedoresCalle

    private void resaltarRegistrarProveedoresNumero(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarProveedoresNumero
        // TODO add your handling code here:
        registrarProveedoresNumero.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresEscribirNumero.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarProveedoresNumero

    private void restaurarRegistrarProveedoresNumero(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarProveedoresNumero
        // TODO add your handling code here:
        registrarProveedoresNumero.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresEscribirNumero.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarProveedoresNumero

    private void resaltarRegistrarProveedoresColonia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resaltarRegistrarProveedoresColonia
        // TODO add your handling code here:
        registrarProveedoresColonia.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresEscribirColonia.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_resaltarRegistrarProveedoresColonia

    private void restaurarRegistrarProveedoresColonia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restaurarRegistrarProveedoresColonia
        // TODO add your handling code here:
        registrarProveedoresColonia.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresEscribirColonia.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_restaurarRegistrarProveedoresColonia

    private void registrarProveedoresEscribirTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProveedoresEscribirTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarProveedoresEscribirTelefonoActionPerformed

    private void verificarRegistrarProveedoresID(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarRegistrarProveedoresID
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (registrarProveedoresEscribirID.getText().length() >= 20) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarRegistrarProveedoresID

    private void verificarRegistrarProveedoresEmpresa(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarRegistrarProveedoresEmpresa
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != '.') && (caracter != '-') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (registrarProveedoresEscribirEmpresa.getText().length() >= 30) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarRegistrarProveedoresEmpresa

    private void verificarRegistrarProveedoresTelefono(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarRegistrarProveedoresTelefono
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C')) {

            evt.consume();
        } else if (registrarProveedoresEscribirTelefono.getText().length() >= 10) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarRegistrarProveedoresTelefono

    private void verificarRegistrarProveedoresCorreo(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarRegistrarProveedoresCorreo
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C') && (caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != '-') && (caracter != '_') && (caracter != '.') && (caracter != '@') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (registrarProveedoresEscribirCorreo.getText().length() >= 70) {
            evt.consume();
        }
    }//GEN-LAST:event_verificarRegistrarProveedoresCorreo

    private void verificarRegistrarProveedoresCalle(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarRegistrarProveedoresCalle
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();
        } else if (registrarProveedoresEscribirCalle.getText().length() >= 30) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarRegistrarProveedoresCalle

    private void verificiarRegistrarProveedoresNumero(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificiarRegistrarProveedoresNumero
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < '0' || caracter > '9' && caracter != 'C') && (caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != 'ñ') && (caracter != 'Ñ')) {

            evt.consume();
        } else if (registrarProveedoresEscribirNumero.getText().length() >= 10) {

            evt.consume();
        }
    }//GEN-LAST:event_verificiarRegistrarProveedoresNumero

    private void verificarRegistrarProveedoresColonia(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificarRegistrarProveedoresColonia
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        if ((caracter < 'a' || caracter > 'z') && (caracter < 'A' || caracter > 'Z') && (caracter != ' ') && (caracter != 'ñ') && (caracter != 'á') && (caracter != 'é') && (caracter != 'í') && (caracter != 'ó') && (caracter != 'ú') && (caracter != 'Ñ') && (caracter != 'Á') && (caracter != 'É') && (caracter != 'Í') && (caracter != 'Ó') && (caracter != 'Ú')) {
            evt.consume();

        } else if (registrarProveedoresEscribirColonia.getText().length() >= 15) {

            evt.consume();
        }
    }//GEN-LAST:event_verificarRegistrarProveedoresColonia

    private void registrarProveedoresBotonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonGuardarMouseEntered
        // TODO add your handling code here:
        registrarProveedoresBotonGuardar.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresBotonGuardar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarProveedoresBotonGuardarMouseEntered

    private void registrarProveedoresBotonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonGuardarMouseExited
        // TODO add your handling code here:
        registrarProveedoresBotonGuardar.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresBotonGuardar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarProveedoresBotonGuardarMouseExited

    private void registrarProveedoresBotonLimpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonLimpiarMouseEntered
        // TODO add your handling code here:
        registrarProveedoresBotonLimpiar.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresBotonLimpiar.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarProveedoresBotonLimpiarMouseEntered

    private void registrarProveedoresBotonLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonLimpiarMouseExited
        // TODO add your handling code here:
        registrarProveedoresBotonLimpiar.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresBotonLimpiar.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarProveedoresBotonLimpiarMouseExited

    private void registrarProveedoresBotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonSalirMouseEntered
        // TODO add your handling code here:
        registrarProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 3, 14));
        registrarProveedoresBotonSalir.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_registrarProveedoresBotonSalirMouseEntered

    private void registrarProveedoresBotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarProveedoresBotonSalirMouseExited
        // TODO add your handling code here:
        registrarProveedoresBotonSalir.setFont(new java.awt.Font("javanese Text", 1, 14));
        registrarProveedoresBotonSalir.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_registrarProveedoresBotonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarProveedores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarProveedores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarProveedores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarProveedores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton registrarProveedoresBotonGuardar;
    private javax.swing.JButton registrarProveedoresBotonLimpiar;
    private javax.swing.JButton registrarProveedoresBotonSalir;
    private javax.swing.JLabel registrarProveedoresCalle;
    private javax.swing.JLabel registrarProveedoresColonia;
    private javax.swing.JLabel registrarProveedoresCorreo;
    private javax.swing.JPanel registrarProveedoresCuerpo;
    private javax.swing.JLabel registrarProveedoresEmpresa;
    private javax.swing.JPanel registrarProveedoresEncabezado;
    private javax.swing.JTextField registrarProveedoresEscribirCalle;
    private javax.swing.JTextField registrarProveedoresEscribirColonia;
    private javax.swing.JTextField registrarProveedoresEscribirCorreo;
    private javax.swing.JTextField registrarProveedoresEscribirEmpresa;
    private javax.swing.JTextField registrarProveedoresEscribirID;
    private javax.swing.JTextField registrarProveedoresEscribirNumero;
    private javax.swing.JTextField registrarProveedoresEscribirTelefono;
    private javax.swing.JLabel registrarProveedoresID;
    private javax.swing.JLabel registrarProveedoresNumero;
    private javax.swing.JPanel registrarProveedoresPie;
    private javax.swing.JLabel registrarProveedoresTelefono;
    private javax.swing.JLabel registrarProveedoresTitulo;
    // End of variables declaration//GEN-END:variables
}
